In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data_3608_20220912.xlsx')

C:\Users\rrr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2472 entries, 0 to 2471
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    2472 non-null   object
 1   종목명     2472 non-null   object
 2   종가      2472 non-null   int64
 3   대비      2472 non-null   int64
 4   등락률     2472 non-null   float64
 5   EPS     2472 non-null   object
 6   PER     2472 non-null   object
 7   선행 EPS  2472 non-null   object
 8   선행 PER  2472 non-null   object
 9   BPS     2472 non-null   object
 10  PBR     2472 non-null   object
 11  주당배당금   2472 non-null   int64
 12  배당수익률   2472 non-null   float64
dtypes: float64(2), int64(3), object(8)
memory usage: 251.2+ KB

In [4]:
df

,종목코드,종목명,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,060310,3S,2840,80,2.90,16,177.5,-,-,792,3.59,0,0.00
1,095570,AJ네트웍스,7990,280,3.63,1707,4.68,856,9.33,8075,0.99,270,3.38
2,006840,AK홀딩스,15750,200,1.29,-,-,-,-,45961,0.34,200,1.27
3,054620,APS홀딩스,13550,150,1.12,1179,11.49,-,-,10088,1.34,100,0.74
4,265520,AP시스템,18850,500,2.72,3932,4.79,3957,4.76,12713,1.48,240,1.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2467,000547,흥국화재2우B,23400,1800,8.33,-,-,-,-,-,-,0,0.00
2468,000545,흥국화재우,6820,90,1.34,-,-,-,-,-,-,0,0.00
2469,003280,흥아해운,1605,40,2.56,118,13.6,-,-,428,3.75,0,0.00
2470,037440,희림,9960,-290,-2.83,490,20.33,-,-,4769,2.09,150,1.51
2471,238490,힘스,7060,260,3.82,-,-,-,-,6598,1.07,100,1.42

In [24]:
df.loc[2470]['종목명']

'희림 '

In [19]:
df['종목명'] = df['종목명'].str.strip()

In [6]:
df_1 = pd.DataFrame({ '종목명':['희림','롯데지주','신한지주']})
df_1

    종목명
0    희림
1  롯데지주
2  신한지주

In [27]:
df_2 = df_1.merge( df,how='left')
df_2

,종목명,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,희림,037440,9960,-290,-2.83,490,20.33,-,-,4769,2.09,150,1.51
1,롯데지주,004990,40900,600,1.49,4315,9.48,3726,10.98,97570,0.42,1500,3.67
2,신한지주,055550,35050,800,2.34,7308,4.8,9370,3.74,88548,0.4,1960,5.59

In [16]:
df3 = pd.read_clipboard()
df3 = df3.rename(columns = {'등락률':'등락률%'})
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N       20 non-null     int64
 1   종목명     20 non-null     object
 2   현재가     20 non-null     object
 3   전일비     20 non-null     object
 4   등락률%    20 non-null     object
 5   거래량     20 non-null     object
 6   거래대금    20 non-null     object
 7   시가총액    20 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.4+ KB

In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N       20 non-null     int64
 1   종목명     20 non-null     object
 2   현재가     20 non-null     object
 3   전일비     20 non-null     object
 4   등락률     20 non-null     object
 5   거래량     20 non-null     object
 6   거래대금    20 non-null     object
 7   시가총액    20 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.4+ KB

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2472 entries, 0 to 2471
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    2472 non-null   object
 1   종목명     2472 non-null   object
 2   종가      2472 non-null   int64
 3   대비      2472 non-null   int64
 4   등락률     2472 non-null   float64
 5   EPS     2472 non-null   object
 6   PER     2472 non-null   object
 7   선행 EPS  2472 non-null   object
 8   선행 PER  2472 non-null   object
 9   BPS     2472 non-null   object
 10  PBR     2472 non-null   object
 11  주당배당금   2472 non-null   int64
 12  배당수익률   2472 non-null   float64
dtypes: float64(2), int64(3), object(8)
memory usage: 251.2+ KB

In [38]:
df4 = df3.merge(df, how='left')
df4

,N,종목명,현재가,전일비,등락률%,거래량,거래대금,시가총액,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,1,매직마이크로,19,하락 5,-20.83%,"42,499,387",924,16,127160,41,-241,-85.46,-,-,-,-,213,0.19,0,0.00
1,2,에코플라스틱,"3,880",상승 165,+4.44%,"37,969,103","156,114","1,326",038110,3685,5,0.14,170,21.68,-,-,3852,0.96,50,1.36
2,3,SM Life Design,"2,575",상승 310,+13.69%,"27,045,658","71,964","1,178",063440,2180,15,0.69,40,54.5,-,-,1068,2.04,0,0.00
3,4,한국전자인증,"7,020","상승 1,020",+17.00%,"24,424,710","172,533","1,334",041460,5460,10,0.18,219,24.93,-,-,2339,2.33,70,1.28
4,5,폴라리스우노,"1,440",상승 140,+10.77%,"17,024,165","26,077",237,114630,1350,0,0.00,98,13.78,-,-,1591,0.85,0,0.00
5,6,지아이텍,"4,685",상승 10,+0.21%,"16,300,233","79,735","1,844",382480,4580,0,0.00,137,33.43,-,-,1331,3.44,22,0.48
6,7,국전약품,"9,260",상승 560,+6.44%,"13,251,119","127,709","4,544",307750,8480,40,0.47,91,93.19,-,-,1695,5,10,0.12
7,8,대동스틸,"6,640","상승 1,490",+28.93%,"12,451,303","80,562",664,048470,4850,-90,-1.82,1463,3.32,-,-,7736,0.63,50,1.03
8,9,모트렉스,"16,450","상승 2,350",+16.67%,"12,181,452","187,075","4,030",118990,13200,-350,-2.58,504,26.19,-,-,5680,2.32,0,0.00
9,10,솔트웨어,"2,030",상승 10,+0.50%,"11,729,938","26,180",647,328380,2000,10,0.50,-,-,-,-,-,-,0,0.00
10,11,SM C&C,"3,860",상승 210,+5.75%,"10,883,129","43,419","3,691",048550,3700,65,1.79,-,-,-,-,1049,3.53,0,0.00
11,12,누보,"2,385",상승 225,+10.42%,"10,853,015","27,519",756,332290,2275,40,1.79,-,-,-,-,1959,1.16,0,0.00
12,13,캠시스,"2,460",상승 130,+5.58%,"10,046,026","24,200","1,816",050110,2215,-5,-0.23,-,-,-,-,1186,1.87,0,0.00
13,14,이트론,179,하락 3,-1.65%,"10,008,726","1,840","1,148",096040,177,-2,-1.12,-,-,-,-,132,1.34,0,0.00
14,15,금강철강,"9,250",상승 150,+1.65%,"9,859,766","97,955","1,732",053260,6990,20,0.29,631,11.08,-,-,7407,0.94,120,1.72
15,16,영우디에스피,"2,115",상승 160,+8.18%,"9,714,564","20,333",943,143540,2035,-10,-0.49,200,10.18,-,-,1420,1.43,0,0.00
16,17,YTN,"3,950",상승 240,+6.47%,"9,571,077","40,411","1,659",040300,3715,25,0.68,1228,3.03,-,-,5759,0.65,50,1.35
17,18,현대바이오,"31,300","하락 9,000",-22.33%,"9,347,518","313,278","12,410",048410,40650,1050,2.65,-,-,-,-,1593,25.52,0,0.00
18,19,리노스,"1,175",하락 60,-4.86%,"8,738,336","10,474",537,039980,939,6,0.64,23,40.83,-,-,1604,0.59,0,0.00
19,20,해성티피씨,"8,740",상승 800,+10.08%,"8,269,893","74,687",827,059270,7480,1270,20.45,-,-,-,-,3827,1.95,0,0.00

In [49]:
df4  = df4.drop(df4[df4.PBR == '-'].index)
df4['PBR'] = df4['PBR'].astype('float')
df4.sort_values('PBR')
df4.loc[ df4.PBR.nsmallest(5).index ]

,N,종목명,현재가,전일비,등락률%,거래량,거래대금,시가총액,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,1,매직마이크로,19,하락 5,-20.83%,"42,499,387",924,16,127160,41,-241,-85.46,-,-,-,-,213,0.19,0,0.00
18,19,리노스,"1,175",하락 60,-4.86%,"8,738,336","10,474",537,039980,939,6,0.64,23,40.83,-,-,1604,0.59,0,0.00
7,8,대동스틸,"6,640","상승 1,490",+28.93%,"12,451,303","80,562",664,048470,4850,-90,-1.82,1463,3.32,-,-,7736,0.63,50,1.03
16,17,YTN,"3,950",상승 240,+6.47%,"9,571,077","40,411","1,659",040300,3715,25,0.68,1228,3.03,-,-,5759,0.65,50,1.35
4,5,폴라리스우노,"1,440",상승 140,+10.77%,"17,024,165","26,077",237,114630,1350,0,0.00,98,13.78,-,-,1591,0.85,0,0.00