In [1]:
import pandas as pd

In [12]:
df_1 = pd.read_excel('forEn.xlsx')

In [13]:
df_1

             name   amount quntity  percent  bns        date
0            삼성전자  270,993    4,448  -0.98%  1.0  2022-08-18
1           NAVER   34,567      138  -0.80% -1.0  2022-08-18
2             현대차   44,367      239  +2.15%  1.0  2022-08-18
3              기아   27,298      355  +0.65% -1.0  2022-08-18
4           삼성SDI   28,431       46  -0.96%  1.0  2022-08-18
...           ...      ...      ...     ...  ...         ...
1010  한국타이어앤테크놀로지    4,539      114  +2.78% -1.0  2022-09-07
1011      솔루스첨단소재    3,391       91  +0.54%  1.0  2022-09-07
1012       한국금융지주    4,520       83  +0.37% -1.0  2022-09-07
1013    SK바이오사이언스    3,309       32  +2.91%  1.0  2022-09-07
1014     현대에너지솔루션    4,520       65  +7.66% -1.0  2022-09-07

[1015 rows x 6 columns]

In [6]:
mList = [ x for x in range(1, df_1['name'].count(), 2 )]
mList

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341,
 343,
 345,
 347,
 349,
 351,
 353,
 355,
 357,
 359,
 361,
 363,
 365,
 367,
 369,
 371,
 373,
 375,
 377,
 379,
 381,
 383,
 385,
 387,
 389,
 391,
 393,
 395,
 397,
 399,
 401,
 403,
 405,
 407,
 409,
 411,
 413,
 415,
 417,
 419,
 421,
 423,
 425,
 427,
 429,
 431,
 433,
 435,
 437,
 439,
 441,
 443,
 445,
 447,
 449,
 451,
 453,
 455,
 457,
 459,
 461,
 463,
 465,
 467,
 469,
 471,
 473,
 475,
 477,
 479,
 481,
 483,
 485,
 487,
 489,
 491,
 493,
 495,
 497,
 499,
 501,
 503,
 505,
 507,
 509,
 511,
 513,
 515,
 517,
 519,
 521,
 523,
 525,
 527,
 529,
 531,
 533,
 535,
 537,
 539,
 541,
 543,
 545,
 547,
 549,
 551,
 553,
 555,
 557,
 559,
 561,
 563,
 565,
 567,
 569,
 571,
 573,
 575,
 577,
 579,
 581,
 583,
 585,
 587,
 589,
 591,
 593,
 595,
 597,
 599,
 601,
 603,
 605,
 607,
 609,
 611,
 613,
 615,
 617,
 619,
 621,
 623,
 625,
 627,
 629,
 631,
 633,
 635,
 637,
 639,
 641,
 643,
 645,
 647,
 649,
 651,
 653,
 655,
 657,
 659,
 661,
 663,
 665,
 667,
 669,
 671,
 673,
 675,
 677,
 679,
 681,
 683,
 685,
 687,
 689,
 691,
 693,
 695,
 697,
 699,
 701,
 703,
 705,
 707,
 709,
 711,
 713,
 715,
 717,
 719,
 721,
 723,
 725,
 727,
 729,
 731,
 733,
 735,
 737,
 739,
 741,
 743,
 745,
 747,
 749,
 751,
 753,
 755,
 757,
 759,
 761,
 763,
 765,
 767,
 769,
 771,
 773,
 775,
 777,
 779,
 781,
 783,
 785,
 787,
 789,
 791,
 793,
 795,
 797,
 799,
 801,
 803,
 805,
 807,
 809,
 811,
 813,
 815,
 817,
 819,
 821,
 823,
 825,
 827,
 829,
 831,
 833,
 835,
 837,
 839,
 841,
 843,
 845,
 847,
 849,
 851,
 853,
 855,
 857,
 859,
 861,
 863,
 865,
 867,
 869,
 871,
 873,
 875,
 877,
 879,
 881,
 883,
 885,
 887,
 889,
 891,
 893,
 895,
 897,
 899,
 901,
 903,
 905,
 907,
 909,
 911,
 913,
 915,
 917,
 919,
 921,
 923,
 925,
 927,
 929,
 931,
 933,
 935,
 937,
 939,
 941,
 943,
 945,
 947,
 949,
 951,
 953,
 955,
 957,
 959,
 961,
 963,
 965,
 967,
 969,
 971,
 973,
 975,
 977,
 979,
 981,
 983,
 985,
 987,
 989,
 991,
 993,
 995,
 997,
 999,
 1001,
 1003,
 1005,
 1007,
 1009,
 1011]

In [40]:
df_1.rename( columns ={ 'name':'종목명','quntity ':'수량'}, inplace =True )

In [41]:
cond1 = df_1.bns == 1.0
df_2 = df_1[cond1]

In [50]:
df_2
df_2.amount = df_2.amount.str.replace(',','')
df_2.수량 = df_2.수량.str.replace(',','')
df_2.amount.astype('int')
df_2.수량.astype('int')
df_2
df_2.columns

C:\Users\rrr\AppData\Local\Temp\ipykernel_14044\2582256885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.amount = df_2.amount.str.replace(',','')
C:\Users\rrr\AppData\Local\Temp\ipykernel_14044\2582256885.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.수량 = df_2.수량.str.replace(',','')

Index(['종목명', 'amount', '수량', 'percent', 'bns', 'date'], dtype='object')

In [53]:
df_2['amount']= df_2['amount'].astype('int')
df_2['수량'] = df_2.수량.astype('int')
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 507 entries, 0 to 1013
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   종목명      507 non-null    object
 1   amount   507 non-null    int32
 2   수량       507 non-null    int32
 3   percent  507 non-null    object
 4   bns      507 non-null    float64
 5   date     507 non-null    object
dtypes: float64(1), int32(2), object(3)
memory usage: 23.8+ KB

C:\Users\rrr\AppData\Local\Temp\ipykernel_14044\2654867943.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['amount']= df_2['amount'].astype('int')
C:\Users\rrr\AppData\Local\Temp\ipykernel_14044\2654867943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['수량'] = df_2.수량.astype('int')

In [67]:
df_3 = df_2[~df_2['종목명'].str.contains('TIGER')]
df_3 = df_2[~df_2['종목명'].str.contains('KODEX')]

In [68]:
df_3

            종목명  amount    수량 percent  bns        date
0          삼성전자  270993  4448  -0.98%  1.0  2022-08-18
2           현대차   44367   239  +2.15%  1.0  2022-08-18
4         삼성SDI   28431    46  -0.96%  1.0  2022-08-18
6       두산에너빌리티   15000   703  -1.40%  1.0  2022-08-18
8         현대모비스   13827    66  +1.66%  1.0  2022-08-18
...         ...     ...   ...     ...  ...         ...
1005       셀트리온    3865    22  +2.51%  1.0  2022-09-07
1007       대한항공    3755   148  +0.20%  1.0  2022-09-07
1009     현대글로비스    3418    21  +1.52%  1.0  2022-09-07
1011    솔루스첨단소재    3391    91  +0.54%  1.0  2022-09-07
1013  SK바이오사이언스    3309    32  +2.91%  1.0  2022-09-07

[481 rows x 6 columns]

In [56]:
df_fn = pd.read_excel('data_3608_20220912.xlsx')

C:\Users\rrr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [59]:
df_fn['종목명'] = df_fn['종목명'].str.strip()

In [69]:
df_4 = df_3.merge(df_fn, how='left')

In [70]:
df_4

,종목명,amount,수량,percent,bns,date,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,삼성전자,270993,4448,-0.98%,1.0,2022-08-18,005930,55600.0,-400.0,-0.71,5777,9.62,5842,9.52,43611,1.27,1444.0,2.60
1,현대차,44367,239,+2.15%,1.0,2022-08-18,005380,200000.0,-2000.0,-0.99,18979,10.54,30294,6.6,289609,0.69,5000.0,2.50
2,삼성SDI,28431,46,-0.96%,1.0,2022-08-18,006400,571000.0,17000.0,3.07,17492,32.64,27198,20.99,219885,2.6,1000.0,0.18
3,두산에너빌리티,15000,703,-1.40%,1.0,2022-08-18,034020,17800.0,-300.0,-1.66,1052,16.92,-,-,11261,1.58,0.0,0.00
4,현대모비스,13827,66,+1.66%,1.0,2022-08-18,012330,219500.0,2500.0,1.15,25645,8.56,33122,6.63,387397,0.57,4000.0,1.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,셀트리온,3865,22,+2.51%,1.0,2022-09-07,068270,184000.0,5000.0,2.79,4134,44.51,5070,36.29,28307,6.5,750.0,0.41
477,대한항공,3755,148,+0.20%,1.0,2022-09-07,003490,25300.0,0.0,0.00,1743,14.52,4303,5.88,19356,1.31,0.0,0.00
478,현대글로비스,3418,21,+1.52%,1.0,2022-09-07,086280,166000.0,1000.0,0.61,20877,7.95,32653,5.08,154732,1.07,3800.0,2.29
479,솔루스첨단소재,3391,91,+0.54%,1.0,2022-09-07,336370,38000.0,700.0,1.88,289,131.49,1029,36.91,7359,5.16,100.0,0.26
480,SK바이오사이언스,3309,32,+2.91%,1.0,2022-09-07,302440,107500.0,4500.0,4.37,4844,22.19,4536,23.7,20932,5.14,0.0,0.00

In [71]:
cand1 = df_4.PBR == '-'
df_5 = df_4[~cond1]

C:\Users\rrr\AppData\Local\Temp\ipykernel_14044\3777941267.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_5 = df_4[~cond1]

In [65]:
df_5

,종목명,amount,수량,percent,bns,date,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
1,현대차,44367,239,+2.15%,1.0,2022-08-18,005380,200000.0,-2000.0,-0.99,18979,10.54,30294,6.6,289609,0.69,5000.0,2.50
3,두산에너빌리티,15000,703,-1.40%,1.0,2022-08-18,034020,17800.0,-300.0,-1.66,1052,16.92,-,-,11261,1.58,0.0,0.00
5,LG화학,13654,21,-1.69%,1.0,2022-08-18,051910,644000.0,21000.0,3.37,47108,13.67,37873,17,278455,2.31,12000.0,1.86
7,포스코케미칼,9459,59,-2.79%,1.0,2022-08-18,003670,169000.0,0.0,0.00,1753,96.41,2937,57.55,30845,5.48,300.0,0.18
9,강원랜드,7314,279,+0.57%,1.0,2022-08-18,035250,25550.0,-200.0,-0.78,-,-,1468,17.41,16044,1.59,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,LX인터내셔널,4816,105,-1.97%,1.0,2022-09-07,001120,44600.0,-1100.0,-2.41,9733,4.58,11426,3.9,49349,0.9,2300.0,5.16
473,현대건설,4316,99,-0.11%,1.0,2022-09-07,000720,43500.0,-500.0,-1.14,3625,12,4822,9.02,64200,0.68,600.0,1.38
475,TIGER 원유선물인버스(H),4022,1208,+2.99%,1.0,2022-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,대한항공,3755,148,+0.20%,1.0,2022-09-07,003490,25300.0,0.0,0.00,1743,14.52,4303,5.88,19356,1.31,0.0,0.00
479,솔루스첨단소재,3391,91,+0.54%,1.0,2022-09-07,336370,38000.0,700.0,1.88,289,131.49,1029,36.91,7359,5.16,100.0,0.26

In [72]:
df_5 = df_5[df_5.PBR.notna()]

In [74]:
df_5

,종목명,amount,수량,percent,bns,date,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
1,현대차,44367,239,+2.15%,1.0,2022-08-18,005380,200000.0,-2000.0,-0.99,18979,10.54,30294,6.6,289609,0.69,5000.0,2.50
3,두산에너빌리티,15000,703,-1.40%,1.0,2022-08-18,034020,17800.0,-300.0,-1.66,1052,16.92,-,-,11261,1.58,0.0,0.00
5,LG화학,13654,21,-1.69%,1.0,2022-08-18,051910,644000.0,21000.0,3.37,47108,13.67,37873,17,278455,2.31,12000.0,1.86
7,포스코케미칼,9459,59,-2.79%,1.0,2022-08-18,003670,169000.0,0.0,0.00,1753,96.41,2937,57.55,30845,5.48,300.0,0.18
9,강원랜드,7314,279,+0.57%,1.0,2022-08-18,035250,25550.0,-200.0,-0.78,-,-,1468,17.41,16044,1.59,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,한국가스공사,5078,129,+1.53%,1.0,2022-09-07,036460,39350.0,250.0,0.64,11078,3.55,12321,3.19,103337,0.38,2728.0,6.93
471,LX인터내셔널,4816,105,-1.97%,1.0,2022-09-07,001120,44600.0,-1100.0,-2.41,9733,4.58,11426,3.9,49349,0.9,2300.0,5.16
473,현대건설,4316,99,-0.11%,1.0,2022-09-07,000720,43500.0,-500.0,-1.14,3625,12,4822,9.02,64200,0.68,600.0,1.38
477,대한항공,3755,148,+0.20%,1.0,2022-09-07,003490,25300.0,0.0,0.00,1743,14.52,4303,5.88,19356,1.31,0.0,0.00
479,솔루스첨단소재,3391,91,+0.54%,1.0,2022-09-07,336370,38000.0,700.0,1.88,289,131.49,1029,36.91,7359,5.16,100.0,0.26

In [77]:
df_6 = df_5[~(df_5['PBR'] == '-')]

In [78]:
df_6['PBR'] = df_6['PBR'].astype('float')
df_6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 226 entries, 1 to 479
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   종목명      226 non-null    object
 1   amount   226 non-null    int32
 2   수량       226 non-null    int32
 3   percent  226 non-null    object
 4   bns      226 non-null    float64
 5   date     226 non-null    object
 6   종목코드     226 non-null    object
 7   종가       226 non-null    float64
 8   대비       226 non-null    float64
 9   등락률      226 non-null    float64
 10  EPS      226 non-null    object
 11  PER      226 non-null    object
 12  선행 EPS   226 non-null    object
 13  선행 PER   226 non-null    object
 14  BPS      226 non-null    object
 15  PBR      226 non-null    float64
 16  주당배당금    226 non-null    float64
 17  배당수익률    226 non-null    float64
dtypes: float64(7), int32(2), object(9)
memory usage: 31.8+ KB

C:\Users\rrr\AppData\Local\Temp\ipykernel_14044\973730210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_6['PBR'] = df_6['PBR'].astype('float')

In [80]:
df_7 = df_6[df_6['PBR'] < 1 ]
df_7

,종목명,amount,수량,percent,bns,date,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
1,현대차,44367,239,+2.15%,1.0,2022-08-18,005380,200000.0,-2000.0,-0.99,18979,10.54,30294,6.6,289609,0.69,5000.0,2.50
23,현대해상,3182,93,+1.32%,1.0,2022-08-18,001450,30600.0,-250.0,-0.81,5286,5.79,5826,5.25,63866,0.48,1480.0,4.84
25,현대위아,3028,44,-0.73%,1.0,2022-08-18,011210,77500.0,-900.0,-1.15,2346,33.03,9080,8.54,122356,0.63,700.0,0.90
33,LG디스플레이,13832,819,-4.73%,1.0,2022-08-19,034220,15200.0,-450.0,-2.88,3315,4.59,-,-,36664,0.41,650.0,4.28
41,현대모비스,7123,33,-0.70%,1.0,2022-08-19,012330,219500.0,2500.0,1.15,25645,8.56,33122,6.63,387397,0.57,4000.0,1.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,현대모비스,2288,11,-1.38%,1.0,2022-09-06,012330,219500.0,2500.0,1.15,25645,8.56,33122,6.63,387397,0.57,4000.0,1.82
455,기아,17757,216,-1.58%,1.0,2022-09-07,000270,80900.0,-1400.0,-1.70,11874,6.81,16237,4.98,87073,0.93,3000.0,3.71
469,한국가스공사,5078,129,+1.53%,1.0,2022-09-07,036460,39350.0,250.0,0.64,11078,3.55,12321,3.19,103337,0.38,2728.0,6.93
471,LX인터내셔널,4816,105,-1.97%,1.0,2022-09-07,001120,44600.0,-1100.0,-2.41,9733,4.58,11426,3.9,49349,0.90,2300.0,5.16
473,현대건설,4316,99,-0.11%,1.0,2022-09-07,000720,43500.0,-500.0,-1.14,3625,12,4822,9.02,64200,0.68,600.0,1.38

In [91]:
df_8 = df_7.sort_values( by='PBR').groupby('종목명').mean()
df_8.sort_values( by ='배당수익률')

,amount,수량,bns,종가,대비,등락률,PBR,주당배당금,배당수익률
종목명,,,,,,,,,
GS글로벌,3484.000000,913.000000,1.0,3425.0,-140.0,-3.93,0.85,0.0,0.00
한국조선해양,7139.000000,74.500000,1.0,88100.0,-200.0,-0.23,0.63,0.0,0.00
한국전력,3627.500000,174.500000,1.0,19650.0,50.0,0.26,0.20,0.0,0.00
현대위아,3028.000000,44.000000,1.0,77500.0,-900.0,-1.15,0.63,700.0,0.90
KG스틸,43848.000000,3915.000000,1.0,10000.0,260.0,2.67,0.87,100.0,1.00
SK이노베이션,9854.000000,49.800000,1.0,189500.0,5000.0,2.71,0.92,2508.0,1.32
농심,6661.000000,21.000000,1.0,289000.0,-500.0,-0.17,0.76,4000.0,1.38
현대건설,4915.333333,110.000000,1.0,43500.0,-500.0,-1.14,0.68,600.0,1.38
유니드,3671.000000,37.000000,1.0,104500.0,0.0,0.00,0.92,1700.0,1.63
현대모비스,6505.250000,30.500000,1.0,219500.0,2500.0,1.15,0.57,4000.0,1.82
OCI,7585.000000,61.333333,1.0,105500.0,0.0,0.00,0.82,2000.0,1.90
팬오션,4518.000000,915.000000,1.0,4830.0,-90.0,-1.83,0.72,100.0,2.07
영원무역,3774.000000,79.000000,1.0,46100.0,2650.0,6.10,0.91,1000.0,2.17
코오롱인더,3637.000000,70.000000,1.0,52200.0,800.0,1.56,0.65,1300.0,2.49
현대차,30935.600000,159.600000,1.0,200000.0,-2000.0,-0.99,0.69,5000.0,2.50
한화,4231.500000,138.500000,1.0,29750.0,-350.0,-1.16,0.57,750.0,2.52
DL,2427.000000,36.000000,1.0,65600.0,100.0,0.15,0.38,1900.0,2.90
HMM,8142.333333,368.666667,1.0,20000.0,350.0,1.78,0.94,600.0,3.00
포스코인터내셔널,7097.857143,263.142857,1.0,25600.0,-600.0,-2.29,0.91,800.0,3.13
현대건설기계,7730.000000,185.000000,1.0,36550.0,450.0,1.25,0.53,1200.0,3.28
삼성물산,5586.000000,47.000000,1.0,116000.0,2000.0,1.75,0.63,4200.0,3.62
SK,5625.500000,25.000000,1.0,219500.0,500.0,0.23,0.59,8000.0,3.64
두산밥캣,2945.000000,84.000000,1.0,32700.0,50.0,0.15,0.76,1200.0,3.67
롯데지주,3961.000000,98.000000,1.0,40900.0,600.0,1.49,0.42,1500.0,3.67
기아,24353.500000,304.000000,1.0,80900.0,-1400.0,-1.70,0.93,3000.0,3.71
LG디스플레이,13832.000000,819.000000,1.0,15200.0,-450.0,-2.88,0.41,650.0,4.28
GS,2916.000000,64.000000,1.0,45400.0,100.0,0.22,0.42,2000.0,4.41
GS건설,5971.000000,197.000000,1.0,28200.0,-150.0,-0.53,0.52,1300.0,4.61
현대해상,3182.000000,93.000000,1.0,30600.0,-250.0,-0.81,0.48,1480.0,4.84
KT,4126.000000,108.000000,1.0,37450.0,1100.0,3.03,0.59,1910.0,5.10
LX인터내셔널,6310.500000,148.500000,1.0,44600.0,-1100.0,-2.41,0.90,2300.0,5.16
신한지주,6980.000000,192.000000,1.0,35050.0,800.0,2.34,0.40,1960.0,5.59
KB금융,12351.000000,256.000000,1.0,48200.0,1350.0,2.88,0.40,2940.0,6.10
SK텔레콤,5144.000000,98.000000,1.0,51900.0,-100.0,-0.19,0.98,3295.0,6.35
DL이앤씨,3157.000000,77.000000,1.0,42150.0,-1000.0,-2.32,0.22,2700.0,6.41
한국가스공사,4565.000000,108.666667,1.0,39350.0,250.0,0.64,0.38,2728.0,6.93
POSCO홀딩스,3660.000000,14.000000,1.0,241500.0,-4500.0,-1.83,0.36,17000.0,7.04
금호석유,4951.000000,38.000000,1.0,127000.0,3000.0,2.42,0.70,10000.0,7.87
우리금융지주,6013.666667,501.333333,1.0,11350.0,50.0,0.44,0.32,900.0,7.93
HD현대,3320.333333,53.333333,1.0,60000.0,-700.0,-1.15,0.67,5550.0,9.25

### 중복되는 항목 제거한다.