# Selenium  WEB Crawing

### selenuim 과 bs4 로 대체 가능

In [1]:
def add( x, y):
    result = x+y
    return(result)

In [38]:
from selenium import webdriver
from selenium.webdriver.common.by import By
#driver = webdriver.Chrome('./chromedriver')
driver = webdriver.Chrome()
daum_investors  =  'https://finance.daum.net/domestic/influential_investors'

In [39]:
driver.get( daum_investors)

In [40]:
#items = driver.find_element('class name','box_contents')
items = driver.find_element(By.CLASS_NAME,'box_contents')
print( items.text )

순매수 종목 순매도 종목
종목명 금액 - 수량 - 등락률 - 종목명 금액 - 수량 - 등락률 -
삼성전자
349,332
4,430
-0.50%
현대차
36,884
150
-3.37%
삼성전자우
108,021
1,627
+1.37%
기아
31,490
275
-2.42%
SK하이닉스
105,286
614
-0.12%
한미반도체
20,194
211
0.00%
삼성SDI
45,976
98
+3.73%
LG디스플레이
18,608
1,718
-4.10%
한화에어로스페이스
45,661
220
+4.28%
KB금융
14,892
198
-1.58%
KODEX 200선물인버스2X
22,184
10,936
+0.25%
POSCO홀딩스
12,857
30
+0.12%
셀트리온
16,488
88
+1.29%
LIG넥스원
12,785
75
+1.58%
엘앤에프
13,233
71
+5.44%
HMM
8,570
546
-2.08%
삼성중공업
12,836
1,428
+2.60%
신한지주
7,750
153
-0.59%
삼성생명
12,155
124
+0.51%
SK텔레콤
7,713
145
0.00%
LG전자
11,930
120
+0.20%
삼성엔지니어링
7,641
308
-3.33%
삼성물산
10,900
67
-3.03%
삼성바이오로직스
6,245
7
-1.98%
하나금융지주
9,149
142
+0.16%
LG생활건강
6,127
16
+1.33%
현대로템
8,487
263
+3.51%
KODEX 코스닥150
5,055
335
+0.17%
SK이노베이션
7,156
59
0.00%
현대오토에버
4,744
32
-1.01%
이수페타시스
6,916
179
+0.13%
TIGER 미국필라델피아반도체나스닥
4,569
262
+1.22%
KT
6,770
174
+1.04%
현대해상
4,458
132
-2.18%
SK스퀘어
6,559
82
+3.90%
하이브
4,343
23
+0.31%
현대차우
5,704
36
-2.16%
오리온
4,090
45
-0.44%
TIGER 미국필라델피아반도체레버리지(합성)
5,543
240
+2.90%
KODEX 200
4,066
108
-0.29%
현대모비스
5,211
20
-1.50%
현대제철
3,680
112
-0.61%
두산에너빌리티
5,124
284
-1.00%
한화오션
3,495
114
+1.15%
하나투어
4,893
70
+2.20%
KODEX 코스닥150레버리지
3,223
243
+0.23%
아모레퍼시픽
4,841
41
+1.57%
NAVER
3,178
17
+2.44%
KODEX 인버스
4,626
1,127
+0.37%
TIGER 은행고배당플러스TOP10
2,701
199
-0.33%
금호석유
4,495
32
-0.50%
알루코
2,541
644
-0.81%
한국전력
4,486
196
-0.22%
삼성전기
2,444
17
-3.14%
삼양식품
4,186
22
+2.22%
메리츠금융지주
2,263
28
+2.93%
LG이노텍
3,942
20
-0.77%
케이씨텍
2,243
53
-5.56%
신풍제약
3,593
216
+28.33%
엔씨소프트
2,204
12
-0.16%

In [13]:
items_ = driver.find_element(By.TAG_NAME, 'table')
items_.text

'코스피\n코스닥\n-\n차트슬라이드'

### List 요소를 4개로 나누어 다시 배열로 만든다.

In [41]:
# List 요소를 4개로 나누어 다시 배열로 만든다.
def list_chuck(arr, n):
    return [arr[i: i + n] for i in range(0, len(arr), n)]

items = driver.find_element('xpath','//*[@id="boxInfluentialInvestors"]/div[2]/div[1]/table')
#print( items.text )
list_items_info = items.text.splitlines() # 텍스트를 라인별로 잘라서 Array 로 만들어 준다.
#print( list_items_info )

del list_items_info[:2]    # 앞에 필요업는 2개 배열요서 제거 
#print( list_items_info )

forEn = list_chuck( list_items_info, 4 )
print( forEn )

[['삼성전자', '349,332', '4,430', '-0.50%'], ['현대차', '36,884', '150', '-3.37%'], ['삼성전자우', '108,021', '1,627', '+1.37%'], ['기아', '31,490', '275', '-2.42%'], ['SK하이닉스', '105,286', '614', '-0.12%'], ['한미반도체', '20,194', '211', '0.00%'], ['삼성SDI', '45,976', '98', '+3.73%'], ['LG디스플레이', '18,608', '1,718', '-4.10%'], ['한화에어로스페이스', '45,661', '220', '+4.28%'], ['KB금융', '14,892', '198', '-1.58%'], ['KODEX 200선물인버스2X', '22,184', '10,936', '+0.25%'], ['POSCO홀딩스', '12,857', '30', '+0.12%'], ['셀트리온', '16,488', '88', '+1.29%'], ['LIG넥스원', '12,785', '75', '+1.58%'], ['엘앤에프', '13,233', '71', '+5.44%'], ['HMM', '8,570', '546', '-2.08%'], ['삼성중공업', '12,836', '1,428', '+2.60%'], ['신한지주', '7,750', '153', '-0.59%'], ['삼성생명', '12,155', '124', '+0.51%'], ['SK텔레콤', '7,713', '145', '0.00%'], ['LG전자', '11,930', '120', '+0.20%'], ['삼성엔지니어링', '7,641', '308', '-3.33%'], ['삼성물산', '10,900', '67', '-3.03%'], ['삼성바이오로직스', '6,245', '7', '-1.98%'], ['하나금융지주', '9,149', '142', '+0.16%'], ['LG생활건강', '6,127', '16', '+1.33%'], ['현대로템', '8,487', '263', '+3.51%'], ['KODEX 코스닥150', '5,055', '335', '+0.17%'], ['SK이노베이션', '7,156', '59', '0.00%'], ['현대오토에버', '4,744', '32', '-1.01%'], ['이수페타시스', '6,916', '179', '+0.13%'], ['TIGER 미국필라델피아반도체나스닥', '4,569', '262', '+1.22%'], ['KT', '6,770', '174', '+1.04%'], ['현대해상', '4,458', '132', '-2.18%'], ['SK스퀘어', '6,559', '82', '+3.90%'], ['하이브', '4,343', '23', '+0.31%'], ['현대차우', '5,704', '36', '-2.16%'], ['오리온', '4,090', '45', '-0.44%'], ['TIGER 미국필라델피아반도체레버리지(합성)', '5,543', '240', '+2.90%'], ['KODEX 200', '4,066', '108', '-0.29%'], ['현대모비스', '5,211', '20', '-1.50%'], ['현대제철', '3,680', '112', '-0.61%'], ['두산에너빌리티', '5,124', '284', '-1.00%'], ['한화오션', '3,495', '114', '+1.15%'], ['하나투어', '4,893', '70', '+2.20%'], ['KODEX 코스닥150레버리지', '3,223', '243', '+0.23%'], ['아모레퍼시픽', '4,841', '41', '+1.57%'], ['NAVER', '3,178', '17', '+2.44%'], ['KODEX 인버스', '4,626', '1,127', '+0.37%'], ['TIGER 은행고배당플러스TOP10', '2,701', '199', '-0.33%'], ['금호석유', '4,495', '32', '-0.50%'], ['알루코', '2,541', '644', '-0.81%'], ['한국전력', '4,486', '196', '-0.22%'], ['삼성전기', '2,444', '17', '-3.14%'], ['삼양식품', '4,186', '22', '+2.22%'], ['메리츠금융지주', '2,263', '28', '+2.93%'], ['LG이노텍', '3,942', '20', '-0.77%'], ['케이씨텍', '2,243', '53', '-5.56%'], ['신풍제약', '3,593', '216', '+28.33%'], ['엔씨소프트', '2,204', '12', '-0.16%']]

In [42]:
import pandas as pd

df = pd.DataFrame(forEn)
df

                           0        1       2        3
0                       삼성전자  349,332   4,430   -0.50%
1                        현대차   36,884     150   -3.37%
2                      삼성전자우  108,021   1,627   +1.37%
3                         기아   31,490     275   -2.42%
4                     SK하이닉스  105,286     614   -0.12%
5                      한미반도체   20,194     211    0.00%
6                      삼성SDI   45,976      98   +3.73%
7                    LG디스플레이   18,608   1,718   -4.10%
8                  한화에어로스페이스   45,661     220   +4.28%
9                       KB금융   14,892     198   -1.58%
10          KODEX 200선물인버스2X   22,184  10,936   +0.25%
11                  POSCO홀딩스   12,857      30   +0.12%
12                      셀트리온   16,488      88   +1.29%
13                    LIG넥스원   12,785      75   +1.58%
14                      엘앤에프   13,233      71   +5.44%
15                       HMM    8,570     546   -2.08%
16                     삼성중공업   12,836   1,428   +2.60%
17                      신한지주    7,750     153   -0.59%
18                      삼성생명   12,155     124   +0.51%
19                     SK텔레콤    7,713     145    0.00%
20                      LG전자   11,930     120   +0.20%
21                   삼성엔지니어링    7,641     308   -3.33%
22                      삼성물산   10,900      67   -3.03%
23                  삼성바이오로직스    6,245       7   -1.98%
24                    하나금융지주    9,149     142   +0.16%
25                    LG생활건강    6,127      16   +1.33%
26                      현대로템    8,487     263   +3.51%
27              KODEX 코스닥150    5,055     335   +0.17%
28                   SK이노베이션    7,156      59    0.00%
29                    현대오토에버    4,744      32   -1.01%
30                    이수페타시스    6,916     179   +0.13%
31       TIGER 미국필라델피아반도체나스닥    4,569     262   +1.22%
32                        KT    6,770     174   +1.04%
33                      현대해상    4,458     132   -2.18%
34                     SK스퀘어    6,559      82   +3.90%
35                       하이브    4,343      23   +0.31%
36                      현대차우    5,704      36   -2.16%
37                       오리온    4,090      45   -0.44%
38  TIGER 미국필라델피아반도체레버리지(합성)    5,543     240   +2.90%
39                 KODEX 200    4,066     108   -0.29%
40                     현대모비스    5,211      20   -1.50%
41                      현대제철    3,680     112   -0.61%
42                   두산에너빌리티    5,124     284   -1.00%
43                      한화오션    3,495     114   +1.15%
44                      하나투어    4,893      70   +2.20%
45          KODEX 코스닥150레버리지    3,223     243   +0.23%
46                    아모레퍼시픽    4,841      41   +1.57%
47                     NAVER    3,178      17   +2.44%
48                 KODEX 인버스    4,626   1,127   +0.37%
49       TIGER 은행고배당플러스TOP10    2,701     199   -0.33%
50                      금호석유    4,495      32   -0.50%
51                       알루코    2,541     644   -0.81%
52                      한국전력    4,486     196   -0.22%
53                      삼성전기    2,444      17   -3.14%
54                      삼양식품    4,186      22   +2.22%
55                   메리츠금융지주    2,263      28   +2.93%
56                     LG이노텍    3,942      20   -0.77%
57                      케이씨텍    2,243      53   -5.56%
58                      신풍제약    3,593     216  +28.33%
59                     엔씨소프트    2,204      12   -0.16%

In [43]:
df.columns =['종목명','금액','수량','등락']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     60 non-null     object
 1   금액      60 non-null     object
 2   수량      60 non-null     object
 3   등락      60 non-null     object
dtypes: object(4)
memory usage: 2.0+ KB

### List 에서 홀수째 열만 뽑아 낸다.

In [44]:
mList = [ x for x in range(1, df['종목명'].count(), 2 )]
mList

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59]

In [45]:
df['금액'] = df['금액'].str.replace(',','')
df['수량'] = df['수량'].str.replace(',','')
# df.drop( index..)
df = df.drop(mList)
df

                         종목명      금액     수량       등락
0                       삼성전자  349332   4430   -0.50%
2                      삼성전자우  108021   1627   +1.37%
4                     SK하이닉스  105286    614   -0.12%
6                      삼성SDI   45976     98   +3.73%
8                  한화에어로스페이스   45661    220   +4.28%
10          KODEX 200선물인버스2X   22184  10936   +0.25%
12                      셀트리온   16488     88   +1.29%
14                      엘앤에프   13233     71   +5.44%
16                     삼성중공업   12836   1428   +2.60%
18                      삼성생명   12155    124   +0.51%
20                      LG전자   11930    120   +0.20%
22                      삼성물산   10900     67   -3.03%
24                    하나금융지주    9149    142   +0.16%
26                      현대로템    8487    263   +3.51%
28                   SK이노베이션    7156     59    0.00%
30                    이수페타시스    6916    179   +0.13%
32                        KT    6770    174   +1.04%
34                     SK스퀘어    6559     82   +3.90%
36                      현대차우    5704     36   -2.16%
38  TIGER 미국필라델피아반도체레버리지(합성)    5543    240   +2.90%
40                     현대모비스    5211     20   -1.50%
42                   두산에너빌리티    5124    284   -1.00%
44                      하나투어    4893     70   +2.20%
46                    아모레퍼시픽    4841     41   +1.57%
48                 KODEX 인버스    4626   1127   +0.37%
50                      금호석유    4495     32   -0.50%
52                      한국전력    4486    196   -0.22%
54                      삼양식품    4186     22   +2.22%
56                     LG이노텍    3942     20   -0.77%
58                      신풍제약    3593    216  +28.33%

In [25]:
df['금액'] = df['금액'].astype('int')
df['수량'] = df['수량'].astype('int')
df.dtypes

### 필요업는 항목의 제목으로 제거하기

In [50]:
df = df[~df['종목명'].str.contains('TIGER')]
df = df[~df['종목명'].str.contains('KODEX')]
df.sort_values( by ='금액')

    level_0  index        종목명      금액    수량       등락
2         2      4     SK하이닉스  105286   614   -0.12%
1         1      2      삼성전자우  108021  1627   +1.37%
10       10     22       삼성물산   10900    67   -3.03%
9         9     20       LG전자   11930   120   +0.20%
8         8     18       삼성생명   12155   124   +0.51%
7         7     16      삼성중공업   12836  1428   +2.60%
6         6     14       엘앤에프   13233    71   +5.44%
5         5     12       셀트리온   16488    88   +1.29%
0         0      0       삼성전자  349332  4430   -0.50%
26       26     58       신풍제약    3593   216  +28.33%
25       25     56      LG이노텍    3942    20   -0.77%
24       24     54       삼양식품    4186    22   +2.22%
23       23     52       한국전력    4486   196   -0.22%
22       22     50       금호석유    4495    32   -0.50%
4         4      8  한화에어로스페이스   45661   220   +4.28%
3         3      6      삼성SDI   45976    98   +3.73%
21       21     46     아모레퍼시픽    4841    41   +1.57%
20       20     44       하나투어    4893    70   +2.20%
19       19     42    두산에너빌리티    5124   284   -1.00%
18       18     40      현대모비스    5211    20   -1.50%
17       17     36       현대차우    5704    36   -2.16%
16       16     34      SK스퀘어    6559    82   +3.90%
15       15     32         KT    6770   174   +1.04%
14       14     30     이수페타시스    6916   179   +0.13%
13       13     28    SK이노베이션    7156    59    0.00%
12       12     26       현대로템    8487   263   +3.51%
11       11     24     하나금융지주    9149   142   +0.16%

## Pandas: getting rid of the multiindex

In [67]:
df.columns = df.columns.map(lambda x: x[1])
df = df.reset_index()

"""
df.columns = df.columns.map(''.join)
#Or if need remove level use droplevel:

df.columns = df.columns.droplevel(0)
#If need access to values is possible use xs:

df = df.xs('CID', axis=1, level=1)
#You can also check:
#What is the difference between size and count in pandas?


EDIT:
For remove MultiIndex is another solution select by ['FID'].


df = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()
Samples (also added rename_axis for nicer output):

df = pd.DataFrame({'CID':[2,2,3],
                   'FE':[5,5,6],
                   'FID':[1,7,9]})

print (df)
   CID  FE  FID
0    2   5    1
1    2   5    7
2    3   6    9

df = df.groupby(by=['CID','FE'])['FID']
       .count()
       .unstack()
       .reset_index()
       .rename_axis(None, axis=1)

print (df)    
   CID    5    6
0    2  2.0  NaN
1    3  NaN  1.0
"""

IndexError: string index out of range

In [62]:
df.index = list( range(0, df['종목명'].count())) 
df

    level_0  index        종목명      금액    수량       등락
0         0      0       삼성전자  349332  4430   -0.50%
1         1      2      삼성전자우  108021  1627   +1.37%
2         2      4     SK하이닉스  105286   614   -0.12%
3         3      6      삼성SDI   45976    98   +3.73%
4         4      8  한화에어로스페이스   45661   220   +4.28%
5         5     12       셀트리온   16488    88   +1.29%
6         6     14       엘앤에프   13233    71   +5.44%
7         7     16      삼성중공업   12836  1428   +2.60%
8         8     18       삼성생명   12155   124   +0.51%
9         9     20       LG전자   11930   120   +0.20%
10       10     22       삼성물산   10900    67   -3.03%
11       11     24     하나금융지주    9149   142   +0.16%
12       12     26       현대로템    8487   263   +3.51%
13       13     28    SK이노베이션    7156    59    0.00%
14       14     30     이수페타시스    6916   179   +0.13%
15       15     32         KT    6770   174   +1.04%
16       16     34      SK스퀘어    6559    82   +3.90%
17       17     36       현대차우    5704    36   -2.16%
18       18     40      현대모비스    5211    20   -1.50%
19       19     42    두산에너빌리티    5124   284   -1.00%
20       20     44       하나투어    4893    70   +2.20%
21       21     46     아모레퍼시픽    4841    41   +1.57%
22       22     50       금호석유    4495    32   -0.50%
23       23     52       한국전력    4486   196   -0.22%
24       24     54       삼양식품    4186    22   +2.22%
25       25     56      LG이노텍    3942    20   -0.77%
26       26     58       신풍제약    3593   216  +28.33%

In [68]:
import os , sys 
dirname = os.path.abspath('')
dirname 

#df_fn = pd.read_excel('data_3608_20220912.xlsx')

'c:\\workdir\\gitdn\\20200228start\\python_ex\\jupyter_note'

In [19]:
df_fn['종목명'] = df_fn['종목명'].str.strip()

In [22]:
df_1 = df.merge(df_fn, how='left')
df_1

,종목명,금액,수량,등락,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,한국항공우주,135436,2424,-7.04%,047810,55500.0,-4200.0,-7.04,656,84.6,1815,30.59,13023,4.26,200.0,0.36
1,삼성SDI,30485,54,+3.07%,006400,571000.0,17000.0,3.07,17492,32.64,27198,20.99,219885,2.6,1000.0,0.18
2,코스모신소재,21720,320,+7.55%,005070,68400.0,4800.0,7.55,604,113.25,1448,47.22,6831,10.01,0.0,0.00
3,LG화학,21428,33,+3.37%,051910,644000.0,21000.0,3.37,47108,13.67,37873,17,278455,2.31,12000.0,1.86
4,LG에너지솔루션,20663,42,-0.31%,373220,486500.0,-1500.0,-0.31,3963,122.76,5771,84.3,39831,12.21,0.0,0.00
5,현대로템,15200,519,+0.86%,064350,29300.0,250.0,0.86,609,48.11,1361,21.53,11847,2.47,0.0,0.00
6,엔씨소프트,11860,32,+0.81%,036570,371500.0,3000.0,0.81,19318,19.23,23091,16.09,155059,2.4,5860.0,1.58
7,코스모화학,11202,403,+9.52%,005420,27600.0,2400.0,9.52,348,79.31,666,41.47,4803,5.75,0.0,0.00
8,LG이노텍,10910,32,+1.66%,011070,337500.0,5500.0,1.66,37537,8.99,51397,6.57,140050,2.41,3000.0,0.89
9,셀트리온,9000,49,+2.79%,068270,184000.0,5000.0,2.79,4134,44.51,5070,36.29,28307,6.5,750.0,0.41
10,포스코인터내셔널,7992,312,-2.29%,047050,25600.0,-600.0,-2.29,2924,8.76,4390,5.83,28259,0.91,800.0,3.13
11,제이알글로벌리츠,7799,1661,+5.92%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,한화에어로스페이스,6972,88,-0.97%,012450,81600.0,-800.0,-0.97,4989,16.36,4646,17.56,57134,1.43,700.0,0.86
13,팬오션,5095,1056,-1.83%,028670,4830.0,-90.0,-1.83,1028,4.7,1270,3.8,6728,0.72,100.0,2.07
14,크래프톤,5089,21,+1.50%,259960,237000.0,3500.0,1.50,12022,19.71,15060,15.74,98465,2.41,0.0,0.00
15,이수화학,4954,183,+15.14%,005950,28900.0,3800.0,15.14,3584,8.06,2127,13.59,10433,2.77,500.0,1.73
16,SKC,4210,38,0.00%,011790,111000.0,0.0,0.00,6174,17.98,5441,20.4,55782,1.99,1100.0,0.99
17,신세계,4113,18,+4.06%,004170,230500.0,9000.0,4.06,31193,7.39,43090,5.35,380637,0.61,3000.0,1.30
18,LX인터내셔널,3822,87,-2.41%,001120,44600.0,-1100.0,-2.41,9733,4.58,11426,3.9,49349,0.9,2300.0,5.16
19,후성,3795,243,+6.89%,093370,16300.0,1050.0,6.89,244,66.8,1372,11.88,2679,6.08,15.0,0.09
20,일진머티리얼즈,3692,55,+1.83%,020150,66600.0,1200.0,1.83,1361,48.93,2344,28.42,21440,3.11,300.0,0.45
21,HMM,2840,142,+1.78%,011200,20000.0,350.0,1.78,13506,1.48,14268,1.4,21179,0.94,600.0,3.00

In [23]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 21
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     22 non-null     object
 1   금액      22 non-null     int32
 2   수량      22 non-null     int32
 3   등락      22 non-null     object
 4   종목코드    21 non-null     object
 5   종가      21 non-null     float64
 6   대비      21 non-null     float64
 7   등락률     21 non-null     float64
 8   EPS     21 non-null     object
 9   PER     21 non-null     object
 10  선행 EPS  21 non-null     object
 11  선행 PER  21 non-null     object
 12  BPS     21 non-null     object
 13  PBR     21 non-null     object
 14  주당배당금   21 non-null     float64
 15  배당수익률   21 non-null     float64
dtypes: float64(5), int32(2), object(9)
memory usage: 2.8+ KB

In [26]:
df_1['PBR'] = df_1['PBR'].astype('float')
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 21
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     22 non-null     object
 1   금액      22 non-null     int32
 2   수량      22 non-null     int32
 3   등락      22 non-null     object
 4   종목코드    21 non-null     object
 5   종가      21 non-null     float64
 6   대비      21 non-null     float64
 7   등락률     21 non-null     float64
 8   EPS     21 non-null     object
 9   PER     21 non-null     object
 10  선행 EPS  21 non-null     object
 11  선행 PER  21 non-null     object
 12  BPS     21 non-null     object
 13  PBR     21 non-null     float64
 14  주당배당금   21 non-null     float64
 15  배당수익률   21 non-null     float64
dtypes: float64(6), int32(2), object(8)
memory usage: 2.8+ KB

In [28]:
df_1

,종목명,금액,수량,등락,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,한국항공우주,135436,2424,-7.04%,047810,55500.0,-4200.0,-7.04,656,84.6,1815,30.59,13023,4.26,200.0,0.36
1,삼성SDI,30485,54,+3.07%,006400,571000.0,17000.0,3.07,17492,32.64,27198,20.99,219885,2.60,1000.0,0.18
2,코스모신소재,21720,320,+7.55%,005070,68400.0,4800.0,7.55,604,113.25,1448,47.22,6831,10.01,0.0,0.00
3,LG화학,21428,33,+3.37%,051910,644000.0,21000.0,3.37,47108,13.67,37873,17,278455,2.31,12000.0,1.86
4,LG에너지솔루션,20663,42,-0.31%,373220,486500.0,-1500.0,-0.31,3963,122.76,5771,84.3,39831,12.21,0.0,0.00
5,현대로템,15200,519,+0.86%,064350,29300.0,250.0,0.86,609,48.11,1361,21.53,11847,2.47,0.0,0.00
6,엔씨소프트,11860,32,+0.81%,036570,371500.0,3000.0,0.81,19318,19.23,23091,16.09,155059,2.40,5860.0,1.58
7,코스모화학,11202,403,+9.52%,005420,27600.0,2400.0,9.52,348,79.31,666,41.47,4803,5.75,0.0,0.00
8,LG이노텍,10910,32,+1.66%,011070,337500.0,5500.0,1.66,37537,8.99,51397,6.57,140050,2.41,3000.0,0.89
9,셀트리온,9000,49,+2.79%,068270,184000.0,5000.0,2.79,4134,44.51,5070,36.29,28307,6.50,750.0,0.41
10,포스코인터내셔널,7992,312,-2.29%,047050,25600.0,-600.0,-2.29,2924,8.76,4390,5.83,28259,0.91,800.0,3.13
11,제이알글로벌리츠,7799,1661,+5.92%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,한화에어로스페이스,6972,88,-0.97%,012450,81600.0,-800.0,-0.97,4989,16.36,4646,17.56,57134,1.43,700.0,0.86
13,팬오션,5095,1056,-1.83%,028670,4830.0,-90.0,-1.83,1028,4.7,1270,3.8,6728,0.72,100.0,2.07
14,크래프톤,5089,21,+1.50%,259960,237000.0,3500.0,1.50,12022,19.71,15060,15.74,98465,2.41,0.0,0.00
15,이수화학,4954,183,+15.14%,005950,28900.0,3800.0,15.14,3584,8.06,2127,13.59,10433,2.77,500.0,1.73
16,SKC,4210,38,0.00%,011790,111000.0,0.0,0.00,6174,17.98,5441,20.4,55782,1.99,1100.0,0.99
17,신세계,4113,18,+4.06%,004170,230500.0,9000.0,4.06,31193,7.39,43090,5.35,380637,0.61,3000.0,1.30
18,LX인터내셔널,3822,87,-2.41%,001120,44600.0,-1100.0,-2.41,9733,4.58,11426,3.9,49349,0.90,2300.0,5.16
19,후성,3795,243,+6.89%,093370,16300.0,1050.0,6.89,244,66.8,1372,11.88,2679,6.08,15.0,0.09
20,일진머티리얼즈,3692,55,+1.83%,020150,66600.0,1200.0,1.83,1361,48.93,2344,28.42,21440,3.11,300.0,0.45
21,HMM,2840,142,+1.78%,011200,20000.0,350.0,1.78,13506,1.48,14268,1.4,21179,0.94,600.0,3.00

In [30]:
df_1 = df_1[df_1['PBR'] < 1 ]
df_1

,종목명,금액,수량,등락,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
10,포스코인터내셔널,7992,312,-2.29%,047050,25600.0,-600.0,-2.29,2924,8.76,4390,5.83,28259,0.91,800.0,3.13
13,팬오션,5095,1056,-1.83%,028670,4830.0,-90.0,-1.83,1028,4.7,1270,3.8,6728,0.72,100.0,2.07
17,신세계,4113,18,+4.06%,004170,230500.0,9000.0,4.06,31193,7.39,43090,5.35,380637,0.61,3000.0,1.30
18,LX인터내셔널,3822,87,-2.41%,001120,44600.0,-1100.0,-2.41,9733,4.58,11426,3.9,49349,0.90,2300.0,5.16
21,HMM,2840,142,+1.78%,011200,20000.0,350.0,1.78,13506,1.48,14268,1.4,21179,0.94,600.0,3.00

In [41]:
from datetime import date 
this_year = date.today().year 
this_month = date.today().month
this_day = date.today().day
this_date_2 = str(this_year)+"-"+str(this_month).zfill(2)+"-"+str(this_day).zfill(2)
print( this_date_2 )

2022-09-12

In [43]:
import os
pwd  = os.getcwd()
df_1.to_excel(pwd+'/forEn_pbr_data/'+this_date_2+'.xlsx')

In [17]:
this_date = driver.find_element('xpath', '//*[@id="labDescription"]/em' )
print( this_date.text )

기준일 : 09.08