# Selenium  WEB Crawing

### selenuim 과 bs4 로 대체 가능

In [1]:
def add( x, y):
    result = x+y
    return(result)

In [21]:
from selenium import webdriver
from selenium.webdriver.common.by import By
#driver = webdriver.Chrome('./chromedriver')
driver = webdriver.Chrome()
daum_investors  =  'https://finance.daum.net/domestic/influential_investors'

In [22]:
driver.get( daum_investors)

In [23]:
#items = driver.find_element('class name','box_contents')
items = driver.find_element(By.CLASS_NAME,'box_contents')
print( items.text )

순매수 종목 순매도 종목
종목명 금액 - 수량 - 등락률 - 종목명 금액 - 수량 - 등락률 -
삼성전자
80,448
1,016
-0.89%
SK하이닉스
63,743
378
-0.24%
한국전력
17,454
784
-1.97%
엘앤에프
27,441
145
+0.11%
하이브
16,651
82
+5.72%
현대차
25,997
108
-1.64%
LG화학
14,046
31
+2.45%
NAVER
22,425
120
-0.48%
삼성물산
12,000
76
-0.94%
삼성전자우
21,268
322
-1.50%
KODEX 200선물인버스2X
11,249
5,580
+0.99%
POSCO홀딩스
10,923
25
+0.82%
신한지주
11,116
221
0.00%
팬오션
8,509
1,986
-5.07%
하나금융지주
10,841
172
-2.19%
현대글로비스
7,807
42
-2.72%
HD현대일렉트릭
9,477
57
+1.80%
현대제철
7,628
235
-1.22%
삼성SDI
8,358
17
+2.86%
LG생활건강
7,437
19
+1.70%
한미약품
8,198
24
+4.20%
신풍제약
6,469
350
+12.67%
포스코퓨처엠
7,909
25
+0.63%
KODEX 레버리지
6,375
317
-0.65%
HLB글로벌
6,729
861
+20.51%
삼성중공업
6,193
686
-1.32%
카카오
6,464
120
+0.37%
오리온
6,152
68
-0.33%
삼성전기
5,995
41
+0.07%
이마트
5,718
83
-1.01%
한미반도체
5,687
57
+3.84%
현대건설
5,386
161
-2.20%
삼성바이오로직스
5,330
6
0.00%
이수스페셜티케미컬
5,268
14
-2.20%
삼양식품
5,164
25
+6.99%
HD현대인프라코어
5,116
624
-3.18%
DB손해보험
4,916
47
+0.87%
기아
5,045
44
-1.24%
고려아연
4,876
10
+3.64%
현대해상
4,682
140
-1.63%
HD한국조선해양
4,425
36
-1.19%
셀트리온
4,575
24
+0.37%
두산에너빌리티
4,366
249
-3.30%
KT
4,419
116
-2.32%
두산
4,323
29
-2.18%
CJ
4,339
38
-5.42%
삼성화재우
4,045
16
+1.78%
LG유플러스
4,258
425
-0.40%
두산밥캣
3,892
77
-3.24%
이수페타시스
4,089
108
-0.13%
현대로템
3,773
115
+0.62%
현대오토에버
4,052
28
-2.38%
코스모신소재
3,747
22
+1.24%
KODEX 코스닥150선물인버스
3,885
1,202
-2.00%
유한양행
3,684
48
+2.10%
SK텔레콤
3,712
70
+0.19%
LIG넥스원
3,595
21
+1.32%
한화오션
3,605
120
-2.28%
에코프로머티
3,507
24
-3.00%
효성첨단소재
3,547
11
-2.99%

In [5]:
items_ = driver.find_element(By.TAG_NAME, 'table')
items_.text

### List 요소를 4개로 나누어 다시 배열로 만든다.

In [24]:
# List 요소를 4개로 나누어 다시 배열로 만든다.
def list_chuck(arr, n):
    return [arr[i: i + n] for i in range(0, len(arr), n)]

items = driver.find_element('xpath','//*[@id="boxInfluentialInvestors"]/div[2]/div[1]/table')
#print( items.text )
list_items_info = items.text.splitlines() # 텍스트를 라인별로 잘라서 Array 로 만들어 준다.
#print( list_items_info )

del list_items_info[:2]    # 앞에 필요업는 2개 배열요서 제거 
#print( list_items_info )

forEn = list_chuck( list_items_info, 4 )
print( forEn )

[['삼성전자', '80,448', '1,016', '-0.89%'], ['SK하이닉스', '63,743', '378', '-0.24%'], ['한국전력', '17,454', '784', '-1.97%'], ['엘앤에프', '27,441', '145', '+0.11%'], ['하이브', '16,651', '82', '+5.72%'], ['현대차', '25,997', '108', '-1.64%'], ['LG화학', '14,046', '31', '+2.45%'], ['NAVER', '22,425', '120', '-0.48%'], ['삼성물산', '12,000', '76', '-0.94%'], ['삼성전자우', '21,268', '322', '-1.50%'], ['KODEX 200선물인버스2X', '11,249', '5,580', '+0.99%'], ['POSCO홀딩스', '10,923', '25', '+0.82%'], ['신한지주', '11,116', '221', '0.00%'], ['팬오션', '8,509', '1,986', '-5.07%'], ['하나금융지주', '10,841', '172', '-2.19%'], ['현대글로비스', '7,807', '42', '-2.72%'], ['HD현대일렉트릭', '9,477', '57', '+1.80%'], ['현대제철', '7,628', '235', '-1.22%'], ['삼성SDI', '8,358', '17', '+2.86%'], ['LG생활건강', '7,437', '19', '+1.70%'], ['한미약품', '8,198', '24', '+4.20%'], ['신풍제약', '6,469', '350', '+12.67%'], ['포스코퓨처엠', '7,909', '25', '+0.63%'], ['KODEX 레버리지', '6,375', '317', '-0.65%'], ['HLB글로벌', '6,729', '861', '+20.51%'], ['삼성중공업', '6,193', '686', '-1.32%'], ['카카오', '6,464', '120', '+0.37%'], ['오리온', '6,152', '68', '-0.33%'], ['삼성전기', '5,995', '41', '+0.07%'], ['이마트', '5,718', '83', '-1.01%'], ['한미반도체', '5,687', '57', '+3.84%'], ['현대건설', '5,386', '161', '-2.20%'], ['삼성바이오로직스', '5,330', '6', '0.00%'], ['이수스페셜티케미컬', '5,268', '14', '-2.20%'], ['삼양식품', '5,164', '25', '+6.99%'], ['HD현대인프라코어', '5,116', '624', '-3.18%'], ['DB손해보험', '4,916', '47', '+0.87%'], ['기아', '5,045', '44', '-1.24%'], ['고려아연', '4,876', '10', '+3.64%'], ['현대해상', '4,682', '140', '-1.63%'], ['HD한국조선해양', '4,425', '36', '-1.19%'], ['셀트리온', '4,575', '24', '+0.37%'], ['두산에너빌리티', '4,366', '249', '-3.30%'], ['KT', '4,419', '116', '-2.32%'], ['두산', '4,323', '29', '-2.18%'], ['CJ', '4,339', '38', '-5.42%'], ['삼성화재우', '4,045', '16', '+1.78%'], ['LG유플러스', '4,258', '425', '-0.40%'], ['두산밥캣', '3,892', '77', '-3.24%'], ['이수페타시스', '4,089', '108', '-0.13%'], ['현대로템', '3,773', '115', '+0.62%'], ['현대오토에버', '4,052', '28', '-2.38%'], ['코스모신소재', '3,747', '22', '+1.24%'], ['KODEX 코스닥150선물인버스', '3,885', '1,202', '-2.00%'], ['유한양행', '3,684', '48', '+2.10%'], ['SK텔레콤', '3,712', '70', '+0.19%'], ['LIG넥스원', '3,595', '21', '+1.32%'], ['한화오션', '3,605', '120', '-2.28%'], ['에코프로머티', '3,507', '24', '-3.00%'], ['효성첨단소재', '3,547', '11', '-2.99%']]

In [25]:
import pandas as pd

df = pd.DataFrame(forEn)
df

                    0       1      2        3
0                삼성전자  80,448  1,016   -0.89%
1              SK하이닉스  63,743    378   -0.24%
2                한국전력  17,454    784   -1.97%
3                엘앤에프  27,441    145   +0.11%
4                 하이브  16,651     82   +5.72%
5                 현대차  25,997    108   -1.64%
6                LG화학  14,046     31   +2.45%
7               NAVER  22,425    120   -0.48%
8                삼성물산  12,000     76   -0.94%
9               삼성전자우  21,268    322   -1.50%
10   KODEX 200선물인버스2X  11,249  5,580   +0.99%
11           POSCO홀딩스  10,923     25   +0.82%
12               신한지주  11,116    221    0.00%
13                팬오션   8,509  1,986   -5.07%
14             하나금융지주  10,841    172   -2.19%
15             현대글로비스   7,807     42   -2.72%
16           HD현대일렉트릭   9,477     57   +1.80%
17               현대제철   7,628    235   -1.22%
18              삼성SDI   8,358     17   +2.86%
19             LG생활건강   7,437     19   +1.70%
20               한미약품   8,198     24   +4.20%
21               신풍제약   6,469    350  +12.67%
22             포스코퓨처엠   7,909     25   +0.63%
23         KODEX 레버리지   6,375    317   -0.65%
24             HLB글로벌   6,729    861  +20.51%
25              삼성중공업   6,193    686   -1.32%
26                카카오   6,464    120   +0.37%
27                오리온   6,152     68   -0.33%
28               삼성전기   5,995     41   +0.07%
29                이마트   5,718     83   -1.01%
30              한미반도체   5,687     57   +3.84%
31               현대건설   5,386    161   -2.20%
32           삼성바이오로직스   5,330      6    0.00%
33          이수스페셜티케미컬   5,268     14   -2.20%
34               삼양식품   5,164     25   +6.99%
35          HD현대인프라코어   5,116    624   -3.18%
36             DB손해보험   4,916     47   +0.87%
37                 기아   5,045     44   -1.24%
38               고려아연   4,876     10   +3.64%
39               현대해상   4,682    140   -1.63%
40           HD한국조선해양   4,425     36   -1.19%
41               셀트리온   4,575     24   +0.37%
42            두산에너빌리티   4,366    249   -3.30%
43                 KT   4,419    116   -2.32%
44                 두산   4,323     29   -2.18%
45                 CJ   4,339     38   -5.42%
46              삼성화재우   4,045     16   +1.78%
47             LG유플러스   4,258    425   -0.40%
48               두산밥캣   3,892     77   -3.24%
49             이수페타시스   4,089    108   -0.13%
50               현대로템   3,773    115   +0.62%
51             현대오토에버   4,052     28   -2.38%
52             코스모신소재   3,747     22   +1.24%
53  KODEX 코스닥150선물인버스   3,885  1,202   -2.00%
54               유한양행   3,684     48   +2.10%
55              SK텔레콤   3,712     70   +0.19%
56             LIG넥스원   3,595     21   +1.32%
57               한화오션   3,605    120   -2.28%
58             에코프로머티   3,507     24   -3.00%
59             효성첨단소재   3,547     11   -2.99%

In [26]:
df.columns =['종목명','금액','수량','등락']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     60 non-null     object
 1   금액      60 non-null     object
 2   수량      60 non-null     object
 3   등락      60 non-null     object
dtypes: object(4)
memory usage: 2.0+ KB

### List 에서 홀수째 열만 뽑아 낸다.

In [27]:
mList = [ x for x in range(1, df['종목명'].count(), 2 )]
mList

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59]

In [28]:
df['금액'] = df['금액'].str.replace(',','')
df['수량'] = df['수량'].str.replace(',','')
# df.drop( index..)
df = df.drop(mList)
df

                 종목명     금액    수량       등락
0               삼성전자  80448  1016   -0.89%
2               한국전력  17454   784   -1.97%
4                하이브  16651    82   +5.72%
6               LG화학  14046    31   +2.45%
8               삼성물산  12000    76   -0.94%
10  KODEX 200선물인버스2X  11249  5580   +0.99%
12              신한지주  11116   221    0.00%
14            하나금융지주  10841   172   -2.19%
16          HD현대일렉트릭   9477    57   +1.80%
18             삼성SDI   8358    17   +2.86%
20              한미약품   8198    24   +4.20%
22            포스코퓨처엠   7909    25   +0.63%
24            HLB글로벌   6729   861  +20.51%
26               카카오   6464   120   +0.37%
28              삼성전기   5995    41   +0.07%
30             한미반도체   5687    57   +3.84%
32          삼성바이오로직스   5330     6    0.00%
34              삼양식품   5164    25   +6.99%
36            DB손해보험   4916    47   +0.87%
38              고려아연   4876    10   +3.64%
40          HD한국조선해양   4425    36   -1.19%
42           두산에너빌리티   4366   249   -3.30%
44                두산   4323    29   -2.18%
46             삼성화재우   4045    16   +1.78%
48              두산밥캣   3892    77   -3.24%
50              현대로템   3773   115   +0.62%
52            코스모신소재   3747    22   +1.24%
54              유한양행   3684    48   +2.10%
56            LIG넥스원   3595    21   +1.32%
58            에코프로머티   3507    24   -3.00%

In [11]:
df['금액'] = df['금액'].astype('int')
df['수량'] = df['수량'].astype('int')
df.dtypes

### 필요업는 항목의 제목으로 제거하기

In [29]:
df = df[~df['종목명'].str.contains('TIGER')]
df = df[~df['종목명'].str.contains('KODEX')]
df.sort_values( by ='금액')

         종목명     금액    수량       등락
14    하나금융지주  10841   172   -2.19%
12      신한지주  11116   221    0.00%
8       삼성물산  12000    76   -0.94%
6       LG화학  14046    31   +2.45%
4        하이브  16651    82   +5.72%
2       한국전력  17454   784   -1.97%
58    에코프로머티   3507    24   -3.00%
56    LIG넥스원   3595    21   +1.32%
54      유한양행   3684    48   +2.10%
52    코스모신소재   3747    22   +1.24%
50      현대로템   3773   115   +0.62%
48      두산밥캣   3892    77   -3.24%
46     삼성화재우   4045    16   +1.78%
44        두산   4323    29   -2.18%
42   두산에너빌리티   4366   249   -3.30%
40  HD한국조선해양   4425    36   -1.19%
38      고려아연   4876    10   +3.64%
36    DB손해보험   4916    47   +0.87%
34      삼양식품   5164    25   +6.99%
32  삼성바이오로직스   5330     6    0.00%
30     한미반도체   5687    57   +3.84%
28      삼성전기   5995    41   +0.07%
26       카카오   6464   120   +0.37%
24    HLB글로벌   6729   861  +20.51%
22    포스코퓨처엠   7909    25   +0.63%
0       삼성전자  80448  1016   -0.89%
20      한미약품   8198    24   +4.20%
18     삼성SDI   8358    17   +2.86%
16  HD현대일렉트릭   9477    57   +1.80%

## Pandas: getting rid of the multiindex

In [30]:
#df.columns = df.columns.map(lambda x: x[1])
df = df.reset_index()

"""
df.columns = df.columns.map(''.join)
#Or if need remove level use droplevel:

df.columns = df.columns.droplevel(0)
#If need access to values is possible use xs:

df = df.xs('CID', axis=1, level=1)
#You can also check:
#What is the difference between size and count in pandas?


EDIT:
For remove MultiIndex is another solution select by ['FID'].


df = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()
Samples (also added rename_axis for nicer output):

df = pd.DataFrame({'CID':[2,2,3],
                   'FE':[5,5,6],
                   'FID':[1,7,9]})

print (df)
   CID  FE  FID
0    2   5    1
1    2   5    7
2    3   6    9

df = df.groupby(by=['CID','FE'])['FID']
       .count()
       .unstack()
       .reset_index()
       .rename_axis(None, axis=1)

print (df)    
   CID    5    6
0    2  2.0  NaN
1    3  NaN  1.0
"""

"\ndf.columns = df.columns.map(''.join)\n#Or if need remove level use droplevel:\n\ndf.columns = df.columns.droplevel(0)\n#If need access to values is possible use xs:\n\ndf = df.xs('CID', axis=1, level=1)\n#You can also check:\n#What is the difference between size and count in pandas?\n\n\nEDIT:\nFor remove MultiIndex is another solution select by ['FID'].\n\n\ndf = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()\nSamples (also added rename_axis for nicer output):\n\ndf = pd.DataFrame({'CID':[2,2,3],\n                   'FE':[5,5,6],\n                   'FID':[1,7,9]})\n\nprint (df)\n   CID  FE  FID\n0    2   5    1\n1    2   5    7\n2    3   6    9\n\ndf = df.groupby(by=['CID','FE'])['FID']\n       .count()\n       .unstack()\n       .reset_index()\n       .rename_axis(None, axis=1)\n\nprint (df)    \n   CID    5    6\n0    2  2.0  NaN\n1    3  NaN  1.0\n"

In [31]:
df

    index       종목명     금액    수량       등락
0       0      삼성전자  80448  1016   -0.89%
1       2      한국전력  17454   784   -1.97%
2       4       하이브  16651    82   +5.72%
3       6      LG화학  14046    31   +2.45%
4       8      삼성물산  12000    76   -0.94%
5      12      신한지주  11116   221    0.00%
6      14    하나금융지주  10841   172   -2.19%
7      16  HD현대일렉트릭   9477    57   +1.80%
8      18     삼성SDI   8358    17   +2.86%
9      20      한미약품   8198    24   +4.20%
10     22    포스코퓨처엠   7909    25   +0.63%
11     24    HLB글로벌   6729   861  +20.51%
12     26       카카오   6464   120   +0.37%
13     28      삼성전기   5995    41   +0.07%
14     30     한미반도체   5687    57   +3.84%
15     32  삼성바이오로직스   5330     6    0.00%
16     34      삼양식품   5164    25   +6.99%
17     36    DB손해보험   4916    47   +0.87%
18     38      고려아연   4876    10   +3.64%
19     40  HD한국조선해양   4425    36   -1.19%
20     42   두산에너빌리티   4366   249   -3.30%
21     44        두산   4323    29   -2.18%
22     46     삼성화재우   4045    16   +1.78%
23     48      두산밥캣   3892    77   -3.24%
24     50      현대로템   3773   115   +0.62%
25     52    코스모신소재   3747    22   +1.24%
26     54      유한양행   3684    48   +2.10%
27     56    LIG넥스원   3595    21   +1.32%
28     58    에코프로머티   3507    24   -3.00%

In [32]:
df.index = list( range(0, df['종목명'].count())) 
df

    index       종목명     금액    수량       등락
0       0      삼성전자  80448  1016   -0.89%
1       2      한국전력  17454   784   -1.97%
2       4       하이브  16651    82   +5.72%
3       6      LG화학  14046    31   +2.45%
4       8      삼성물산  12000    76   -0.94%
5      12      신한지주  11116   221    0.00%
6      14    하나금융지주  10841   172   -2.19%
7      16  HD현대일렉트릭   9477    57   +1.80%
8      18     삼성SDI   8358    17   +2.86%
9      20      한미약품   8198    24   +4.20%
10     22    포스코퓨처엠   7909    25   +0.63%
11     24    HLB글로벌   6729   861  +20.51%
12     26       카카오   6464   120   +0.37%
13     28      삼성전기   5995    41   +0.07%
14     30     한미반도체   5687    57   +3.84%
15     32  삼성바이오로직스   5330     6    0.00%
16     34      삼양식품   5164    25   +6.99%
17     36    DB손해보험   4916    47   +0.87%
18     38      고려아연   4876    10   +3.64%
19     40  HD한국조선해양   4425    36   -1.19%
20     42   두산에너빌리티   4366   249   -3.30%
21     44        두산   4323    29   -2.18%
22     46     삼성화재우   4045    16   +1.78%
23     48      두산밥캣   3892    77   -3.24%
24     50      현대로템   3773   115   +0.62%
25     52    코스모신소재   3747    22   +1.24%
26     54      유한양행   3684    48   +2.10%
27     56    LIG넥스원   3595    21   +1.32%
28     58    에코프로머티   3507    24   -3.00%

In [41]:
import os , sys 
from os import listdir
dirname = os.path.abspath('')
dirname = os.path.normpath( os.path.join( dirname , '../examples[data-source]/f_xls/data_krx' ) )
last_file = listdir( dirname  )[-1]
last_file 
file_path = os.path.join( dirname ,  last_file )
#df_fn = pd.read_excel('data_3608_20220912.xlsx')
df_fn = pd.read_excel(file_path)

c:\python38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [42]:
df_fn['종목명'] = df_fn['종목명'].str.strip()

In [43]:
df_1 = df.merge(df_fn, how='left')
df_1

,index,종목명,금액,수량,등락,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,0,삼성전자,80448,1016,-0.89%,005930,78900,-400,-0.50,8057,9.79,4709,16.76,57822,1.36,1444,1.83
1,2,한국전력,17454,784,-1.97%,015760,22800,-50,-0.22,-,-,8058,2.83,63158,0.36,0,0.00
2,4,하이브,16651,82,+5.72%,352820,195800,600,0.31,1265,154.78,7478,26.18,66995,2.92,0,0.00
3,6,LG화학,14046,31,+2.45%,051910,449500,10500,2.39,23670,18.99,29251,15.37,445524,1.01,10000,2.22
4,8,삼성물산,12000,76,-0.94%,028260,160000,-5000,-3.03,12460,12.84,12830,12.47,164524,0.97,2300,1.44
5,12,신한지주,11116,221,0.00%,055550,50600,-300,-0.59,8454,5.99,9280,5.45,95206,0.53,2065,4.08
6,14,하나금융지주,10841,172,-2.19%,086790,64000,100,0.16,11803,5.42,12727,5.03,124935,0.51,3350,5.23
7,16,HD현대일렉트릭,9477,57,+1.80%,267260,166500,3900,2.40,4514,36.89,9105,18.29,22854,7.29,500,0.30
8,18,삼성SDI,8358,17,+2.86%,006400,472500,17000,3.73,29191,16.19,29027,16.28,251948,1.88,1030,0.22
9,20,한미약품,8198,24,+4.20%,128940,333000,-1000,-0.30,6523,51.05,12018,27.71,68808,4.84,500,0.15
10,22,포스코퓨처엠,7909,25,+0.63%,003670,318500,0,0.00,1527,208.58,2970,107.25,31922,9.98,300,0.09
11,24,HLB글로벌,6729,861,+20.51%,003580,6730,-210,-3.03,-,-,-,-,1507,4.47,0,0.00
12,26,카카오,6464,120,+0.37%,035720,53600,0,0.00,3106,17.26,1116,48.03,22893,2.34,60,0.11
13,28,삼성전기,5995,41,+0.07%,009150,144900,-4700,-3.14,12977,11.17,8532,16.98,103702,1.4,2100,1.45
14,30,한미반도체,5687,57,+3.84%,042700,93800,0,0.00,939,99.89,1515,61.93,4008,23.4,200,0.21
15,32,삼성바이오로직스,5330,6,0.00%,207940,840000,-17000,-1.98,11442,73.41,14281,58.82,126233,6.65,0,0.00
16,34,삼양식품,5164,25,+6.99%,003230,193000,4200,2.22,10665,18.1,18949,10.19,60733,3.18,1400,0.73
17,36,DB손해보험,4916,47,+0.87%,005830,103600,500,0.48,16373,6.33,20030,5.17,89508,1.16,4600,4.44
18,38,고려아연,4876,10,+3.64%,010130,440000,-1500,-0.34,42967,10.24,28219,15.59,455251,0.97,20000,4.55
19,40,HD한국조선해양,4425,36,-1.19%,009540,125900,-2000,-1.56,-,-,12378,10.17,137382,0.92,0,0.00
20,42,두산에너빌리티,4366,249,-3.30%,034020,17890,-180,-1.00,-,-,432,41.44,11146,1.61,0,0.00
21,44,두산,4323,29,-2.18%,000150,147000,-3600,-2.39,-,-,9498,15.48,132422,1.11,2000,1.36
22,46,삼성화재우,4045,16,+1.78%,000815,252500,2500,1.00,-,-,-,-,-,-,13805,5.47
23,48,두산밥캣,3892,77,-3.24%,241560,52400,-800,-1.50,6421,8.16,7689,6.81,50136,1.05,1350,2.58
24,50,현대로템,3773,115,+0.62%,064350,32400,1100,3.51,1812,17.88,2216,14.62,13930,2.33,0,0.00
25,52,코스모신소재,3747,22,+1.24%,005070,169200,-300,-0.18,901,187.79,2230,75.87,8099,20.89,0,0.00
26,54,유한양행,3684,48,+2.10%,000100,76300,0,0.00,1272,59.98,2169,35.18,27137,2.81,400,0.52
27,56,LIG넥스원,3595,21,+1.32%,079550,167300,2600,1.58,5641,29.66,9595,17.44,42909,3.9,1500,0.90
28,58,에코프로머티,3507,24,-3.00%,450080,149800,-900,-0.60,294,509.52,-,-,5428,27.6,0,0.00

In [46]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   29 non-null     int64
 1   종목명     29 non-null     object
 2   금액      29 non-null     object
 3   수량      29 non-null     object
 4   등락      29 non-null     object
 5   종목코드    29 non-null     object
 6   종가      29 non-null     int64
 7   대비      29 non-null     int64
 8   등락률     29 non-null     float64
 9   EPS     29 non-null     object
 10  PER     29 non-null     object
 11  선행 EPS  29 non-null     object
 12  선행 PER  29 non-null     object
 13  BPS     29 non-null     object
 14  PBR     29 non-null     object
 15  주당배당금   29 non-null     int64
 16  배당수익률   29 non-null     float64
dtypes: float64(2), int64(4), object(11)
memory usage: 4.0+ KB

In [47]:
df_1['PBR'] = df_1['PBR'].astype('float')
df_1.info()

ValueError: could not convert string to float: '-'

In [ ]:
df_1

In [45]:
df_1 = df_1[df_1['PBR'] < 1 ]
df_1

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
from datetime import date 
this_year = date.today().year 
this_month = date.today().month
this_day = date.today().day
this_date_2 = str(this_year)+"-"+str(this_month).zfill(2)+"-"+str(this_day).zfill(2)
print( this_date_2 )

In [ ]:
import os
pwd  = os.getcwd()
df_1.to_excel(pwd+'/forEn_pbr_data/'+this_date_2+'.xlsx')

In [ ]:
this_date = driver.find_element('xpath', '//*[@id="labDescription"]/em' )
print( this_date.text )