# Selenium  WEB Crawing

### selenuim 과 bs4 로 대체 가능

In [1]:
def add( x, y):
    result = x+y
    return(result)

In [8]:
from selenium import webdriver
from selenium.webdriver.common.by import By
#driver = webdriver.Chrome('./chromedriver')
driver = webdriver.Chrome()
daum_investors  =  'https://finance.daum.net/domestic/influential_investors'

In [9]:
driver.get( daum_investors)

In [10]:
#items = driver.find_element('class name','box_contents')
items = driver.find_element(By.CLASS_NAME,'box_contents')
print( items.text )

순매수 종목 순매도 종목
종목명 금액 - 수량 - 등락률 - 종목명 금액 - 수량 - 등락률 -
SK하이닉스
211,587
1,166
+2.60%
신한지주
52,911
1,108
-5.53%
현대차
40,189
164
+1.46%
LG화학
31,625
71
-1.11%
에이피알
33,931
131
+5.29%
POSCO홀딩스
22,845
53
-0.23%
크래프톤
22,492
87
+4.26%
NAVER
19,759
104
+0.21%
삼성물산
22,161
140
-1.50%
하나투어
14,345
225
-10.26%
이수페타시스
21,423
471
+11.75%
메리츠금융지주
14,196
174
-5.54%
한화에어로스페이스
20,912
95
+3.24%
LG에너지솔루션
13,381
33
+0.74%
현대로템
20,121
596
+3.31%
LG디스플레이
11,517
1,089
-1.94%
하나금융지주
13,167
220
-4.07%
HMM
8,213
526
+0.52%
삼성생명
12,426
131
-3.78%
기아
4,957
43
-0.70%
에코프로머티
11,894
86
-1.42%
LG전자
4,826
50
+0.21%
하이브
10,843
49
+6.92%
LG생활건강
4,803
12
+3.16%
두산밥캣
10,302
192
+11.09%
엔씨소프트
4,594
22
-0.24%
삼성SDI
9,969
20
+1.59%
한올바이오파마
4,546
116
-4.09%
삼성전자
9,696
121
-0.13%
TIGER 미국필라델피아반도체나스닥
4,378
251
+0.14%
현대차우
9,025
56
+2.36%
셀트리온
4,253
24
-1.18%
TIGER 미국필라델피아반도체레버리지(합성)
8,110
351
+0.30%
HD현대일렉트릭
3,813
21
-0.49%
엘앤에프
6,587
35
-1.20%
SK이노베이션
3,707
31
+0.08%
KODEX 200선물인버스2X
6,462
3,172
-0.05%
카카오뱅크
3,662
130
-2.25%
LG이노텍
5,305
27
+1.67%
우리금융지주
3,631
243
-3.37%
풍산
5,077
101
+2.42%
현대제철
3,594
110
+0.15%
삼성전자우
4,858
73
+0.30%
TIGER 미국테크TOP10 INDXX
3,568
200
-0.06%
포스코퓨처엠
4,509
14
-0.79%
KB금융
3,534
50
-3.90%
KCC
4,451
16
-1.64%
한국항공우주
3,395
67
+0.20%
기업은행
4,076
274
-2.70%
S-Oil
3,165
40
-1.64%
TIGER 미국S&P500
3,851
220
+0.57%
부광약품
3,121
392
+2.10%
현대글로비스
3,533
19
+1.20%
KODEX 인버스
3,113
755
-0.12%
솔루스첨단소재
3,372
201
+29.94%
KODEX 코스닥150
3,036
195
-0.81%
롯데관광개발
3,213
324
+5.71%
한화솔루션
2,903
107
-0.37%
삼성바이오로직스
3,106
4
+0.97%
삼성화재
2,847
9
-2.54%

In [11]:
items_ = driver.find_element(By.TAG_NAME, 'table')
items_.text

'코스피\n코스닥\n-\n차트슬라이드'

### List 요소를 4개로 나누어 다시 배열로 만든다.

In [12]:
# List 요소를 4개로 나누어 다시 배열로 만든다.
def list_chuck(arr, n):
    return [arr[i: i + n] for i in range(0, len(arr), n)]

items = driver.find_element('xpath','//*[@id="boxInfluentialInvestors"]/div[2]/div[1]/table')
#print( items.text )
list_items_info = items.text.splitlines() # 텍스트를 라인별로 잘라서 Array 로 만들어 준다.
#print( list_items_info )

del list_items_info[:2]    # 앞에 필요업는 2개 배열요서 제거 
#print( list_items_info )

forEn = list_chuck( list_items_info, 4 )
print( forEn )

[['SK하이닉스', '211,587', '1,166', '+2.60%'], ['신한지주', '52,911', '1,108', '-5.53%'], ['현대차', '40,189', '164', '+1.46%'], ['LG화학', '31,625', '71', '-1.11%'], ['에이피알', '33,931', '131', '+5.29%'], ['POSCO홀딩스', '22,845', '53', '-0.23%'], ['크래프톤', '22,492', '87', '+4.26%'], ['NAVER', '19,759', '104', '+0.21%'], ['삼성물산', '22,161', '140', '-1.50%'], ['하나투어', '14,345', '225', '-10.26%'], ['이수페타시스', '21,423', '471', '+11.75%'], ['메리츠금융지주', '14,196', '174', '-5.54%'], ['한화에어로스페이스', '20,912', '95', '+3.24%'], ['LG에너지솔루션', '13,381', '33', '+0.74%'], ['현대로템', '20,121', '596', '+3.31%'], ['LG디스플레이', '11,517', '1,089', '-1.94%'], ['하나금융지주', '13,167', '220', '-4.07%'], ['HMM', '8,213', '526', '+0.52%'], ['삼성생명', '12,426', '131', '-3.78%'], ['기아', '4,957', '43', '-0.70%'], ['에코프로머티', '11,894', '86', '-1.42%'], ['LG전자', '4,826', '50', '+0.21%'], ['하이브', '10,843', '49', '+6.92%'], ['LG생활건강', '4,803', '12', '+3.16%'], ['두산밥캣', '10,302', '192', '+11.09%'], ['엔씨소프트', '4,594', '22', '-0.24%'], ['삼성SDI', '9,969', '20', '+1.59%'], ['한올바이오파마', '4,546', '116', '-4.09%'], ['삼성전자', '9,696', '121', '-0.13%'], ['TIGER 미국필라델피아반도체나스닥', '4,378', '251', '+0.14%'], ['현대차우', '9,025', '56', '+2.36%'], ['셀트리온', '4,253', '24', '-1.18%'], ['TIGER 미국필라델피아반도체레버리지(합성)', '8,110', '351', '+0.30%'], ['HD현대일렉트릭', '3,813', '21', '-0.49%'], ['엘앤에프', '6,587', '35', '-1.20%'], ['SK이노베이션', '3,707', '31', '+0.08%'], ['KODEX 200선물인버스2X', '6,462', '3,172', '-0.05%'], ['카카오뱅크', '3,662', '130', '-2.25%'], ['LG이노텍', '5,305', '27', '+1.67%'], ['우리금융지주', '3,631', '243', '-3.37%'], ['풍산', '5,077', '101', '+2.42%'], ['현대제철', '3,594', '110', '+0.15%'], ['삼성전자우', '4,858', '73', '+0.30%'], ['TIGER 미국테크TOP10 INDXX', '3,568', '200', '-0.06%'], ['포스코퓨처엠', '4,509', '14', '-0.79%'], ['KB금융', '3,534', '50', '-3.90%'], ['KCC', '4,451', '16', '-1.64%'], ['한국항공우주', '3,395', '67', '+0.20%'], ['기업은행', '4,076', '274', '-2.70%'], ['S-Oil', '3,165', '40', '-1.64%'], ['TIGER 미국S&P500', '3,851', '220', '+0.57%'], ['부광약품', '3,121', '392', '+2.10%'], ['현대글로비스', '3,533', '19', '+1.20%'], ['KODEX 인버스', '3,113', '755', '-0.12%'], ['솔루스첨단소재', '3,372', '201', '+29.94%'], ['KODEX 코스닥150', '3,036', '195', '-0.81%'], ['롯데관광개발', '3,213', '324', '+5.71%'], ['한화솔루션', '2,903', '107', '-0.37%'], ['삼성바이오로직스', '3,106', '4', '+0.97%'], ['삼성화재', '2,847', '9', '-2.54%']]

In [13]:
import pandas as pd

df = pd.DataFrame(forEn)
df

                           0        1      2        3
0                     SK하이닉스  211,587  1,166   +2.60%
1                       신한지주   52,911  1,108   -5.53%
2                        현대차   40,189    164   +1.46%
3                       LG화학   31,625     71   -1.11%
4                       에이피알   33,931    131   +5.29%
5                   POSCO홀딩스   22,845     53   -0.23%
6                       크래프톤   22,492     87   +4.26%
7                      NAVER   19,759    104   +0.21%
8                       삼성물산   22,161    140   -1.50%
9                       하나투어   14,345    225  -10.26%
10                    이수페타시스   21,423    471  +11.75%
11                   메리츠금융지주   14,196    174   -5.54%
12                 한화에어로스페이스   20,912     95   +3.24%
13                  LG에너지솔루션   13,381     33   +0.74%
14                      현대로템   20,121    596   +3.31%
15                   LG디스플레이   11,517  1,089   -1.94%
16                    하나금융지주   13,167    220   -4.07%
17                       HMM    8,213    526   +0.52%
18                      삼성생명   12,426    131   -3.78%
19                        기아    4,957     43   -0.70%
20                    에코프로머티   11,894     86   -1.42%
21                      LG전자    4,826     50   +0.21%
22                       하이브   10,843     49   +6.92%
23                    LG생활건강    4,803     12   +3.16%
24                      두산밥캣   10,302    192  +11.09%
25                     엔씨소프트    4,594     22   -0.24%
26                     삼성SDI    9,969     20   +1.59%
27                   한올바이오파마    4,546    116   -4.09%
28                      삼성전자    9,696    121   -0.13%
29       TIGER 미국필라델피아반도체나스닥    4,378    251   +0.14%
30                      현대차우    9,025     56   +2.36%
31                      셀트리온    4,253     24   -1.18%
32  TIGER 미국필라델피아반도체레버리지(합성)    8,110    351   +0.30%
33                  HD현대일렉트릭    3,813     21   -0.49%
34                      엘앤에프    6,587     35   -1.20%
35                   SK이노베이션    3,707     31   +0.08%
36          KODEX 200선물인버스2X    6,462  3,172   -0.05%
37                     카카오뱅크    3,662    130   -2.25%
38                     LG이노텍    5,305     27   +1.67%
39                    우리금융지주    3,631    243   -3.37%
40                        풍산    5,077    101   +2.42%
41                      현대제철    3,594    110   +0.15%
42                     삼성전자우    4,858     73   +0.30%
43     TIGER 미국테크TOP10 INDXX    3,568    200   -0.06%
44                    포스코퓨처엠    4,509     14   -0.79%
45                      KB금융    3,534     50   -3.90%
46                       KCC    4,451     16   -1.64%
47                    한국항공우주    3,395     67   +0.20%
48                      기업은행    4,076    274   -2.70%
49                     S-Oil    3,165     40   -1.64%
50            TIGER 미국S&P500    3,851    220   +0.57%
51                      부광약품    3,121    392   +2.10%
52                    현대글로비스    3,533     19   +1.20%
53                 KODEX 인버스    3,113    755   -0.12%
54                   솔루스첨단소재    3,372    201  +29.94%
55              KODEX 코스닥150    3,036    195   -0.81%
56                    롯데관광개발    3,213    324   +5.71%
57                     한화솔루션    2,903    107   -0.37%
58                  삼성바이오로직스    3,106      4   +0.97%
59                      삼성화재    2,847      9   -2.54%

In [14]:
df.columns =['종목명','금액','수량','등락']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     60 non-null     object
 1   금액      60 non-null     object
 2   수량      60 non-null     object
 3   등락      60 non-null     object
dtypes: object(4)
memory usage: 2.0+ KB

# BeautifulSoup으로 Crawling

In [9]:
from bs4 import BeautifulSoup
from selenium import webdriver
import urllib 
import pandas as pd
daum_investors  =  'https://finance.daum.net/domestic/influential_investors?market=KOSPI'
"""
html_table = urllib.request.urlopen( daum_investors ).read() 
"""

driver = webdriver.Chrome()
driver.get(daum_investors)
html_table = driver.page_source

soup = BeautifulSoup( html_table, "html.parser")

for table in soup.find_all('table'):
    print( table )

table = pd.read_html( str( soup), flavor="bs4")
print( table[1] )

<table class="tab">
<colgroup>
<col width="100"/>
<col width="100"/>
<col width="*"/>
</colgroup>
<tbody>
<tr>
<td class="on"><a href="?market=KOSPI" title="코스피">코스피</a></td>
<td class=""><a href="?market=KOSDAQ" title="코스닥">코스닥</a></td>
<td class="last">
<a class="btnChart" href="/domestic/chart_slides/influential_investors?market=KOSPI" title="차트슬라이드"><i>-</i>차트슬라이드</a>
</td>
</tr>
</tbody>
</table>
<table>
<colgroup>
<col width="*"/>
<col width="74"/>
<col width="64"/>
<col width="74"/>
<col width="120"/>
<col width="74"/>
<col width="64"/>
<col width="74"/>
</colgroup>
<thead>
<tr>
<th class="red" colspan="4">순매수 종목</th>
<th class="blue" colspan="4">순매도 종목</th>
</tr>
<tr>
<th class="lAlign">종목명</th>
<th class="rAlign">
<a class="" data-field-name="straightPurchasePrice" data-field-type="buy" href="javascript:void(0)">
                금액 <i>-</i>
</a>
</th>
<th class="rAlign">
            &lt;a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="buy"&gt;
                수량 <i>-</i>

</th>
<th class="rAlign last">
            &lt;a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="buy"&gt;
                등락률 <i>-</i>

</th>
<th class="pL lAlign">종목명</th>
<th class="rAlign">
<a class="on" data-field-name="straightPurchasePrice" data-field-type="sell" href="javascript:void(0)">
                금액 <i>-</i>
</a>
</th>
<th class="rAlign">
            &lt;a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="sell"&gt;
                수량 <i>-</i>

</th>
<th class="rAlign last">
            &lt;a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="sell"&gt;
                등락률 <i>-</i>

</th>
</tr>
</thead>
<tbody>
<tr class="first">
<td>
<a class="txt" href="/quotes/A005930">삼성전자</a>
</td>
<td>
<span class="num">402,261</span>
</td>
<td>
<span class="num">5,000</span>
</td>
<td class="pR">
<span class="num up">+1.25%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A068270">셀트리온</a>
</td>
<td>
<span class="num">85,798</span>
</td>
<td>
<span class="num">496</span>
</td>
<td class="pR">
<span class="num down">-0.22%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A042700">한미반도체</a>
</td>
<td>
<span class="num">55,086</span>
</td>
<td>
<span class="num">419</span>
</td>
<td class="pR">
<span class="num up">+17.13%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A000660">SK하이닉스</a>
</td>
<td>
<span class="num">56,942</span>
</td>
<td>
<span class="num">318</span>
</td>
<td class="pR">
<span class="num down">-1.66%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A105560">KB금융</a>
</td>
<td>
<span class="num">31,708</span>
</td>
<td>
<span class="num">451</span>
</td>
<td class="pR">
<span class="num up">+1.88%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A005380">현대차</a>
</td>
<td>
<span class="num">56,345</span>
</td>
<td>
<span class="num">235</span>
</td>
<td class="pR">
<span class="num down">-2.87%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A028260">삼성물산</a>
</td>
<td>
<span class="num">23,431</span>
</td>
<td>
<span class="num">148</span>
</td>
<td class="pR">
<span class="num up">+1.52%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A005490">POSCO홀딩스</a>
</td>
<td>
<span class="num">38,095</span>
</td>
<td>
<span class="num">90</span>
</td>
<td class="pR">
<span class="num down">-1.64%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A005935">삼성전자우</a>
</td>
<td>
<span class="num">16,877</span>
</td>
<td>
<span class="num">252</span>
</td>
<td class="pR">
<span class="num up">+0.60%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A373220">LG에너지솔루션</a>
</td>
<td>
<span class="num">30,508</span>
</td>
<td>
<span class="num">76</span>
</td>
<td class="pR">
<span class="num down">-1.83%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A012330">현대모비스</a>
</td>
<td>
<span class="num">11,430</span>
</td>
<td>
<span class="num">44</span>
</td>
<td class="pR">
<span class="num down">-1.13%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A035420">NAVER</a>
</td>
<td>
<span class="num">28,651</span>
</td>
<td>
<span class="num">152</span>
</td>
<td class="pR">
<span class="num down">-1.16%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A066570">LG전자</a>
</td>
<td>
<span class="num">9,893</span>
</td>
<td>
<span class="num">102</span>
</td>
<td class="pR">
<span class="num down">-0.21%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A012450">한화에어로스페이스</a>
</td>
<td>
<span class="num">23,533</span>
</td>
<td>
<span class="num">110</span>
</td>
<td class="pR">
<span class="num down">-6.95%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A316140">우리금융지주</a>
</td>
<td>
<span class="num">8,929</span>
</td>
<td>
<span class="num">614</span>
</td>
<td class="pR">
<span class="num down">-0.14%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A051910">LG화학</a>
</td>
<td>
<span class="num">14,361</span>
</td>
<td>
<span class="num">33</span>
</td>
<td class="pR">
<span class="num down">-0.90%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A352820">하이브</a>
</td>
<td>
<span class="num">8,330</span>
</td>
<td>
<span class="num">36</span>
</td>
<td class="pR">
<span class="num up">+2.23%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A259960">크래프톤</a>
</td>
<td>
<span class="num">10,703</span>
</td>
<td>
<span class="num">43</span>
</td>
<td class="pR">
<span class="num down">-2.72%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A064350">현대로템</a>
</td>
<td>
<span class="num">7,615</span>
</td>
<td>
<span class="num">223</span>
</td>
<td class="pR">
<span class="num up">+0.29%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A004020">현대제철</a>
</td>
<td>
<span class="num">10,271</span>
</td>
<td>
<span class="num">322</span>
</td>
<td class="pR">
<span class="num down">-2.45%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A450080">에코프로머티</a>
</td>
<td>
<span class="num">6,325</span>
</td>
<td>
<span class="num">47</span>
</td>
<td class="pR">
<span class="num down">-4.02%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A307950">현대오토에버</a>
</td>
<td>
<span class="num">10,028</span>
</td>
<td>
<span class="num">67</span>
</td>
<td class="pR">
<span class="num down">-2.45%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A032830">삼성생명</a>
</td>
<td>
<span class="num">5,860</span>
</td>
<td>
<span class="num">62</span>
</td>
<td class="pR">
<span class="num up">+1.49%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A003670">포스코퓨처엠</a>
</td>
<td>
<span class="num">10,026</span>
</td>
<td>
<span class="num">33</span>
</td>
<td class="pR">
<span class="num down">-3.04%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A423920">TIGER 미국필라델피아반도체레버리지(합성)</a>
</td>
<td>
<span class="num">5,752</span>
</td>
<td>
<span class="num">245</span>
</td>
<td class="pR">
<span class="num up">+0.34%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A252670">KODEX 200선물인버스2X</a>
</td>
<td>
<span class="num">9,062</span>
</td>
<td>
<span class="num">4,584</span>
</td>
<td class="pR">
<span class="num up">+0.05%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A000100">유한양행</a>
</td>
<td>
<span class="num">5,545</span>
</td>
<td>
<span class="num">72</span>
</td>
<td class="pR">
<span class="num up">+1.44%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A051900">LG생활건강</a>
</td>
<td>
<span class="num">8,679</span>
</td>
<td>
<span class="num">22</span>
</td>
<td class="pR">
<span class="num down">-1.40%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A086790">하나금융지주</a>
</td>
<td>
<span class="num">5,312</span>
</td>
<td>
<span class="num">91</span>
</td>
<td class="pR">
<span class="num">0.00%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A381180">TIGER 미국필라델피아반도체나스닥</a>
</td>
<td>
<span class="num">8,424</span>
</td>
<td>
<span class="num">480</span>
</td>
<td class="pR">
<span class="num up">+0.14%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A402340">SK스퀘어</a>
</td>
<td>
<span class="num">4,929</span>
</td>
<td>
<span class="num">62</span>
</td>
<td class="pR">
<span class="num down">-0.88%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A278470">에이피알</a>
</td>
<td>
<span class="num">8,144</span>
</td>
<td>
<span class="num">30</span>
</td>
<td class="pR">
<span class="num down">-5.92%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A371460">TIGER 차이나전기차SOLACTIVE</a>
</td>
<td>
<span class="num">4,910</span>
</td>
<td>
<span class="num">637</span>
</td>
<td class="pR">
<span class="num down">-0.26%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A001040">CJ</a>
</td>
<td>
<span class="num">7,807</span>
</td>
<td>
<span class="num">65</span>
</td>
<td class="pR">
<span class="num up">+5.34%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A454910">두산로보틱스</a>
</td>
<td>
<span class="num">4,816</span>
</td>
<td>
<span class="num">55</span>
</td>
<td class="pR">
<span class="num down">-1.23%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A005070">코스모신소재</a>
</td>
<td>
<span class="num">7,337</span>
</td>
<td>
<span class="num">45</span>
</td>
<td class="pR">
<span class="num down">-4.13%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A005385">현대차우</a>
</td>
<td>
<span class="num">4,572</span>
</td>
<td>
<span class="num">29</span>
</td>
<td class="pR">
<span class="num down">-1.43%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A006400">삼성SDI</a>
</td>
<td>
<span class="num">6,186</span>
</td>
<td>
<span class="num">13</span>
</td>
<td class="pR">
<span class="num down">-0.62%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A010060">OCI홀딩스</a>
</td>
<td>
<span class="num">4,263</span>
</td>
<td>
<span class="num">45</span>
</td>
<td class="pR">
<span class="num down">-0.53%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A001570">금양</a>
</td>
<td>
<span class="num">5,929</span>
</td>
<td>
<span class="num">51</span>
</td>
<td class="pR">
<span class="num down">-1.05%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A011070">LG이노텍</a>
</td>
<td>
<span class="num">3,805</span>
</td>
<td>
<span class="num">19</span>
</td>
<td class="pR">
<span class="num up">+1.39%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A241560">두산밥캣</a>
</td>
<td>
<span class="num">5,866</span>
</td>
<td>
<span class="num">105</span>
</td>
<td class="pR">
<span class="num down">-3.74%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A010660">화천기계</a>
</td>
<td>
<span class="num">3,285</span>
</td>
<td>
<span class="num">513</span>
</td>
<td class="pR">
<span class="num down">-9.25%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A009830">한화솔루션</a>
</td>
<td>
<span class="num">5,547</span>
</td>
<td>
<span class="num">194</span>
</td>
<td class="pR">
<span class="num up">+2.03%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A364980">TIGER 2차전지TOP10</a>
</td>
<td>
<span class="num">3,214</span>
</td>
<td>
<span class="num">217</span>
</td>
<td class="pR">
<span class="num down">-1.84%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A034730">SK</a>
</td>
<td>
<span class="num">5,125</span>
</td>
<td>
<span class="num">28</span>
</td>
<td class="pR">
<span class="num down">-1.40%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A298050">효성첨단소재</a>
</td>
<td>
<span class="num">3,154</span>
</td>
<td>
<span class="num">9</span>
</td>
<td class="pR">
<span class="num up">+1.49%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A010120">LS ELECTRIC</a>
</td>
<td>
<span class="num">4,824</span>
</td>
<td>
<span class="num">48</span>
</td>
<td class="pR">
<span class="num down">-0.40%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A024110">기업은행</a>
</td>
<td>
<span class="num">3,129</span>
</td>
<td>
<span class="num">224</span>
</td>
<td class="pR">
<span class="num down">-5.68%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A022100">포스코DX</a>
</td>
<td>
<span class="num">4,655</span>
</td>
<td>
<span class="num">95</span>
</td>
<td class="pR">
<span class="num down">-4.43%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A042670">HD현대인프라코어</a>
</td>
<td>
<span class="num">3,048</span>
</td>
<td>
<span class="num">352</span>
</td>
<td class="pR">
<span class="num up">+1.42%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A036570">엔씨소프트</a>
</td>
<td>
<span class="num">4,592</span>
</td>
<td>
<span class="num">22</span>
</td>
<td class="pR">
<span class="num down">-0.72%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A108320">LX세미콘</a>
</td>
<td>
<span class="num">2,860</span>
</td>
<td>
<span class="num">36</span>
</td>
<td class="pR">
<span class="num up">+1.13%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A305720">KODEX 2차전지산업</a>
</td>
<td>
<span class="num">4,340</span>
</td>
<td>
<span class="num">195</span>
</td>
<td class="pR">
<span class="num down">-1.84%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A039490">키움증권</a>
</td>
<td>
<span class="num">2,648</span>
</td>
<td>
<span class="num">21</span>
</td>
<td class="pR">
<span class="num down">-1.20%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A005387">현대차2우B</a>
</td>
<td>
<span class="num">4,294</span>
</td>
<td>
<span class="num">27</span>
</td>
<td class="pR">
<span class="num down">-1.75%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A175330">JB금융지주</a>
</td>
<td>
<span class="num">2,632</span>
</td>
<td>
<span class="num">201</span>
</td>
<td class="pR">
<span class="num down">-1.29%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A272210">한화시스템</a>
</td>
<td>
<span class="num">4,242</span>
</td>
<td>
<span class="num">244</span>
</td>
<td class="pR">
<span class="num down">-2.71%</span>
</td>
</tr>
<tr class="last last">
<td>
<a class="txt" href="/quotes/A009150">삼성전기</a>
</td>
<td>
<span class="num">2,624</span>
</td>
<td>
<span class="num">17</span>
</td>
<td class="pR">
<span class="num up">+0.40%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A007660">이수페타시스</a>
</td>
<td>
<span class="num">4,177</span>
</td>
<td>
<span class="num">90</span>
</td>
<td class="pR">
<span class="num up">+2.63%</span>
</td>
</tr>
</tbody>
</table>

                      순매수 종목
                         종목명    금액 -
0                       삼성전자  402261  \
1                      한미반도체   55086
2                       KB금융   31708
3                       삼성물산   23431
4                      삼성전자우   16877
5                      현대모비스   11430
6                       LG전자    9893
7                     우리금융지주    8929
8                        하이브    8330
9                       현대로템    7615
10                    에코프로머티    6325
11                      삼성생명    5860
12  TIGER 미국필라델피아반도체레버리지(합성)    5752
13                      유한양행    5545
14                    하나금융지주    5312
15                     SK스퀘어    4929
16     TIGER 차이나전기차SOLACTIVE    4910
17                    두산로보틱스    4816
18                      현대차우    4572
19                    OCI홀딩스    4263
20                     LG이노텍    3805
21                      화천기계    3285
22           TIGER 2차전지TOP10    3214
23                    효성첨단소재    3154
24                      기업은행    3129
25                 HD현대인프라코어    3048
26                     LX세미콘    2860
27                      키움증권    2648
28                    JB금융지주    2632
29                      삼성전기    2624


   <a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="buy">  수량 -
0                                                5000                                                                \
1                                                 419
2                                                 451
3                                                 148
4                                                 252
5                                                  44
6                                                 102
7                                                 614
8                                                  36
9                                                 223
10                                                 47
11                                                 62
12                                                245
13                                                 72
14                                                 91
15                                                 62
16                                                637
17                                                 55
18                                                 29
19                                                 45
20                                                 19
21                                                513
22                                                217
23                                                  9
24                                                224
25                                                352
26                                                 36
27                                                 21
28                                                201
29                                                 17


   <a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="buy">  등락률 -
0                                              +1.25%                                                     \
1                                             +17.13%
2                                              +1.88%
3                                              +1.52%
4                                              +0.60%
5                                              -1.13%
6                                              -0.21%
7                                              -0.14%
8                                              +2.23%
9                                              +0.29%
10                                             -4.02%
11                                             +1.49%
12                                             +0.34%
13                                             +1.44%
14                                              0.00%
15                                             -0.88%
16                                             -0.26%
17                                             -1.23%
18                                             -1.43%
19                                             -0.53%
20                                             +1.39%
21                                             -9.25%
22                                             -1.84%
23                                             +1.49%
24                                             -5.68%
25                                             +1.42%
26                                             +1.13%
27                                             -1.20%
28                                             -1.29%
29                                             +0.40%

                 순매도 종목
                    종목명   금액 -
0                  셀트리온  85798  \
1                SK하이닉스  56942
2                   현대차  56345
3              POSCO홀딩스  38095
4              LG에너지솔루션  30508
5                 NAVER  28651
6             한화에어로스페이스  23533
7                  LG화학  14361
8                  크래프톤  10703
9                  현대제철  10271
10               현대오토에버  10028
11               포스코퓨처엠  10026
12     KODEX 200선물인버스2X   9062
13               LG생활건강   8679
14  TIGER 미국필라델피아반도체나스닥   8424
15                 에이피알   8144
16                   CJ   7807
17               코스모신소재   7337
18                삼성SDI   6186
19                   금양   5929
20                 두산밥캣   5866
21                한화솔루션   5547
22                   SK   5125
23          LS ELECTRIC   4824
24                포스코DX   4655
25                엔씨소프트   4592
26         KODEX 2차전지산업   4340
27               현대차2우B   4294
28                한화시스템   4242
29               이수페타시스   4177


   <a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="sell">  수량 -
0                                                 496                                                                 \
1                                                 318
2                                                 235
3                                                  90
4                                                  76
5                                                 152
6                                                 110
7                                                  33
8                                                  43
9                                                 322
10                                                 67
11                                                 33
12                                               4584
13                                                 22
14                                                480
15                                                 30
16                                                 65
17                                                 45
18                                                 13
19                                                 51
20                                                105
21                                                194
22                                                 28
23                                                 48
24                                                 95
25                                                 22
26                                                195
27                                                 27
28                                                244
29                                                 90


   <a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="sell">  등락률 -
0                                              -0.22%
1                                              -1.66%
2                                              -2.87%
3                                              -1.64%
4                                              -1.83%
5                                              -1.16%
6                                              -6.95%
7                                              -0.90%
8                                              -2.72%
9                                              -2.45%
10                                             -2.45%
11                                             -3.04%
12                                             +0.05%
13                                             -1.40%
14                                             +0.14%
15                                             -5.92%
16                                             +5.34%
17                                             -4.13%
18                                             -0.62%
19                                             -1.05%
20                                             -3.74%
21                                             +2.03%
22                                             -1.40%
23                                             -0.40%
24                                             -4.43%
25                                             -0.72%
26                                             -1.84%
27                                             -1.75%
28                                             -2.71%
29                                             +2.63%

###  Pandas: drop a level from a multi-level column index?

cols = pd.MultiIndex.from_tuples([("a", "b"), ("a", "c")])

In [17]:
df_1 = table[1]
df_1.columns

df_1.drop( columns = [('순매도 종목')] )

C:\Users\star_\AppData\Local\Temp\ipykernel_9908\126042991.py:4: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df_1.drop( columns = [('순매도 종목')] )

                      순매수 종목
                         종목명    금액 -
0                       삼성전자  402261  \
1                      한미반도체   55086
2                       KB금융   31708
3                       삼성물산   23431
4                      삼성전자우   16877
5                      현대모비스   11430
6                       LG전자    9893
7                     우리금융지주    8929
8                        하이브    8330
9                       현대로템    7615
10                    에코프로머티    6325
11                      삼성생명    5860
12  TIGER 미국필라델피아반도체레버리지(합성)    5752
13                      유한양행    5545
14                    하나금융지주    5312
15                     SK스퀘어    4929
16     TIGER 차이나전기차SOLACTIVE    4910
17                    두산로보틱스    4816
18                      현대차우    4572
19                    OCI홀딩스    4263
20                     LG이노텍    3805
21                      화천기계    3285
22           TIGER 2차전지TOP10    3214
23                    효성첨단소재    3154
24                      기업은행    3129
25                 HD현대인프라코어    3048
26                     LX세미콘    2860
27                      키움증권    2648
28                    JB금융지주    2632
29                      삼성전기    2624


   <a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="buy">  수량 -
0                                                5000                                                                \
1                                                 419
2                                                 451
3                                                 148
4                                                 252
5                                                  44
6                                                 102
7                                                 614
8                                                  36
9                                                 223
10                                                 47
11                                                 62
12                                                245
13                                                 72
14                                                 91
15                                                 62
16                                                637
17                                                 55
18                                                 29
19                                                 45
20                                                 19
21                                                513
22                                                217
23                                                  9
24                                                224
25                                                352
26                                                 36
27                                                 21
28                                                201
29                                                 17


   <a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="buy">  등락률 -
0                                              +1.25%
1                                             +17.13%
2                                              +1.88%
3                                              +1.52%
4                                              +0.60%
5                                              -1.13%
6                                              -0.21%
7                                              -0.14%
8                                              +2.23%
9                                              +0.29%
10                                             -4.02%
11                                             +1.49%
12                                             +0.34%
13                                             +1.44%
14                                              0.00%
15                                             -0.88%
16                                             -0.26%
17                                             -1.23%
18                                             -1.43%
19                                             -0.53%
20                                             +1.39%
21                                             -9.25%
22                                             -1.84%
23                                             +1.49%
24                                             -5.68%
25                                             +1.42%
26                                             +1.13%
27                                             -1.20%
28                                             -1.29%
29                                             +0.40%

### List 에서 홀수째 열만 뽑아 낸다.

In [15]:
mList = [ x for x in range(1, df['종목명'].count(), 2 )]
mList

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59]

In [16]:
df['금액'] = df['금액'].str.replace(',','')
df['수량'] = df['수량'].str.replace(',','')
# df.drop( index..)
df = df.drop(mList)
df

                         종목명      금액    수량       등락
0                     SK하이닉스  211587  1166   +2.60%
2                        현대차   40189   164   +1.46%
4                       에이피알   33931   131   +5.29%
6                       크래프톤   22492    87   +4.26%
8                       삼성물산   22161   140   -1.50%
10                    이수페타시스   21423   471  +11.75%
12                 한화에어로스페이스   20912    95   +3.24%
14                      현대로템   20121   596   +3.31%
16                    하나금융지주   13167   220   -4.07%
18                      삼성생명   12426   131   -3.78%
20                    에코프로머티   11894    86   -1.42%
22                       하이브   10843    49   +6.92%
24                      두산밥캣   10302   192  +11.09%
26                     삼성SDI    9969    20   +1.59%
28                      삼성전자    9696   121   -0.13%
30                      현대차우    9025    56   +2.36%
32  TIGER 미국필라델피아반도체레버리지(합성)    8110   351   +0.30%
34                      엘앤에프    6587    35   -1.20%
36          KODEX 200선물인버스2X    6462  3172   -0.05%
38                     LG이노텍    5305    27   +1.67%
40                        풍산    5077   101   +2.42%
42                     삼성전자우    4858    73   +0.30%
44                    포스코퓨처엠    4509    14   -0.79%
46                       KCC    4451    16   -1.64%
48                      기업은행    4076   274   -2.70%
50            TIGER 미국S&P500    3851   220   +0.57%
52                    현대글로비스    3533    19   +1.20%
54                   솔루스첨단소재    3372   201  +29.94%
56                    롯데관광개발    3213   324   +5.71%
58                  삼성바이오로직스    3106     4   +0.97%

In [17]:
df['금액'] = df['금액'].astype('int')
df['수량'] = df['수량'].astype('int')
df.dtypes

종목명    object
금액      int32
수량      int32
등락     object
dtype: object

### 필요업는 항목의 제목으로 제거하기

In [18]:
df = df[~df['종목명'].str.contains('TIGER')]
df = df[~df['종목명'].str.contains('KODEX')]
df.sort_values( by ='금액', ascending = False )

          종목명      금액    수량       등락
0      SK하이닉스  211587  1166   +2.60%
2         현대차   40189   164   +1.46%
4        에이피알   33931   131   +5.29%
6        크래프톤   22492    87   +4.26%
8        삼성물산   22161   140   -1.50%
10     이수페타시스   21423   471  +11.75%
12  한화에어로스페이스   20912    95   +3.24%
14       현대로템   20121   596   +3.31%
16     하나금융지주   13167   220   -4.07%
18       삼성생명   12426   131   -3.78%
20     에코프로머티   11894    86   -1.42%
22        하이브   10843    49   +6.92%
24       두산밥캣   10302   192  +11.09%
26      삼성SDI    9969    20   +1.59%
28       삼성전자    9696   121   -0.13%
30       현대차우    9025    56   +2.36%
34       엘앤에프    6587    35   -1.20%
38      LG이노텍    5305    27   +1.67%
40         풍산    5077   101   +2.42%
42      삼성전자우    4858    73   +0.30%
44     포스코퓨처엠    4509    14   -0.79%
46        KCC    4451    16   -1.64%
48       기업은행    4076   274   -2.70%
52     현대글로비스    3533    19   +1.20%
54    솔루스첨단소재    3372   201  +29.94%
56     롯데관광개발    3213   324   +5.71%
58   삼성바이오로직스    3106     4   +0.97%

## Pandas: getting rid of the multiindex

In [19]:
#df.columns = df.columns.map(lambda x: x[1])
df = df.reset_index()

"""
df.columns = df.columns.map(''.join)
#Or if need remove level use droplevel:

df.columns = df.columns.droplevel(0)
#If need access to values is possible use xs:

df = df.xs('CID', axis=1, level=1)
#You can also check:
#What is the difference between size and count in pandas?


EDIT:
For remove MultiIndex is another solution select by ['FID'].


df = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()
Samples (also added rename_axis for nicer output):

df = pd.DataFrame({'CID':[2,2,3],
                   'FE':[5,5,6],
                   'FID':[1,7,9]})

print (df)
   CID  FE  FID
0    2   5    1
1    2   5    7
2    3   6    9

df = df.groupby(by=['CID','FE'])['FID']
       .count()
       .unstack()
       .reset_index()
       .rename_axis(None, axis=1)

print (df)    
   CID    5    6
0    2  2.0  NaN
1    3  NaN  1.0
"""

"\ndf.columns = df.columns.map(''.join)\n#Or if need remove level use droplevel:\n\ndf.columns = df.columns.droplevel(0)\n#If need access to values is possible use xs:\n\ndf = df.xs('CID', axis=1, level=1)\n#You can also check:\n#What is the difference between size and count in pandas?\n\n\nEDIT:\nFor remove MultiIndex is another solution select by ['FID'].\n\n\ndf = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()\nSamples (also added rename_axis for nicer output):\n\ndf = pd.DataFrame({'CID':[2,2,3],\n                   'FE':[5,5,6],\n                   'FID':[1,7,9]})\n\nprint (df)\n   CID  FE  FID\n0    2   5    1\n1    2   5    7\n2    3   6    9\n\ndf = df.groupby(by=['CID','FE'])['FID']\n       .count()\n       .unstack()\n       .reset_index()\n       .rename_axis(None, axis=1)\n\nprint (df)    \n   CID    5    6\n0    2  2.0  NaN\n1    3  NaN  1.0\n"

In [ ]:
df

In [20]:
df.index = list( range(0, df['종목명'].count())) 
df

    index        종목명      금액    수량       등락
0       0     SK하이닉스  211587  1166   +2.60%
1       2        현대차   40189   164   +1.46%
2       4       에이피알   33931   131   +5.29%
3       6       크래프톤   22492    87   +4.26%
4       8       삼성물산   22161   140   -1.50%
5      10     이수페타시스   21423   471  +11.75%
6      12  한화에어로스페이스   20912    95   +3.24%
7      14       현대로템   20121   596   +3.31%
8      16     하나금융지주   13167   220   -4.07%
9      18       삼성생명   12426   131   -3.78%
10     20     에코프로머티   11894    86   -1.42%
11     22        하이브   10843    49   +6.92%
12     24       두산밥캣   10302   192  +11.09%
13     26      삼성SDI    9969    20   +1.59%
14     28       삼성전자    9696   121   -0.13%
15     30       현대차우    9025    56   +2.36%
16     34       엘앤에프    6587    35   -1.20%
17     38      LG이노텍    5305    27   +1.67%
18     40         풍산    5077   101   +2.42%
19     42      삼성전자우    4858    73   +0.30%
20     44     포스코퓨처엠    4509    14   -0.79%
21     46        KCC    4451    16   -1.64%
22     48       기업은행    4076   274   -2.70%
23     52     현대글로비스    3533    19   +1.20%
24     54    솔루스첨단소재    3372   201  +29.94%
25     56     롯데관광개발    3213   324   +5.71%
26     58   삼성바이오로직스    3106     4   +0.97%

### KRX 에서 받은 현재 전종목 PBR PER DIV 엑셀과 Join

In [21]:
import os , sys 
from os import listdir
dirname = os.path.abspath('')
dirname = os.path.normpath( os.path.join( dirname , '../examples[data-source]/f_xls/data_krx' ) )
last_file = listdir( dirname  )[-1]
last_file 
file_path = os.path.join( dirname ,  last_file )
#df_fn = pd.read_excel('data_3608_20220912.xlsx')
df_fn = pd.read_excel(file_path)

c:\python38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [22]:
df_fn['종목명'] = df_fn['종목명'].str.strip()

In [23]:
df_1 = df.merge(df_fn, how='left')
df_1

,index,종목명,금액,수량,등락,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,0,SK하이닉스,211587,1166,+2.60%,000660,169800,-200,-0.12,3242,52.38,12187,13.93,92004,1.85,1200,0.71
1,2,현대차,40189,164,+1.46%,005380,243500,-8500,-3.37,28521,8.54,43093,5.65,407147,0.6,7000,2.87
2,4,에이피알,33931,131,+5.29%,278470,258500,-500,-0.19,4221,61.24,-,-,13953,18.53,0,0.00
3,6,크래프톤,22492,87,+4.26%,259960,236000,-4500,-1.87,10666,22.13,13799,17.1,108962,2.17,0,0.00
4,8,삼성물산,22161,140,-1.50%,028260,160000,-5000,-3.03,12460,12.84,12830,12.47,164524,0.97,2300,1.44
5,10,이수페타시스,21423,471,+11.75%,007660,37650,50,0.13,1620,23.24,1440,26.15,3515,10.71,100,0.27
6,12,한화에어로스페이스,20912,95,+3.24%,012450,202000,8300,4.28,3964,50.96,11937,16.92,56612,3.57,1000,0.50
7,14,현대로템,20121,596,+3.31%,064350,32400,1100,3.51,1812,17.88,2216,14.62,13930,2.33,0,0.00
8,16,하나금융지주,13167,220,-4.07%,086790,64000,100,0.16,11803,5.42,12727,5.03,124935,0.51,3350,5.23
9,18,삼성생명,12426,131,-3.78%,032830,97900,500,0.51,8817,11.1,10071,9.72,124081,0.79,3000,3.06
10,20,에코프로머티,11894,86,-1.42%,450080,149800,-900,-0.60,294,509.52,-,-,5428,27.6,0,0.00
11,22,하이브,10843,49,+6.92%,352820,195800,600,0.31,1265,154.78,7478,26.18,66995,2.92,0,0.00
12,24,두산밥캣,10302,192,+11.09%,241560,52400,-800,-1.50,6421,8.16,7689,6.81,50136,1.05,1350,2.58
13,26,삼성SDI,9969,20,+1.59%,006400,472500,17000,3.73,29191,16.19,29027,16.28,251948,1.88,1030,0.22
14,28,삼성전자,9696,121,-0.13%,005930,78900,-400,-0.50,8057,9.79,4709,16.76,57822,1.36,1444,1.83
15,30,현대차우,9025,56,+2.36%,005385,158700,-3500,-2.16,-,-,-,-,-,-,7050,4.44
16,34,엘앤에프,6587,35,-1.20%,066970,186100,9600,5.44,8269,22.51,620,299.99,38454,4.84,500,0.27
17,38,LG이노텍,5305,27,+1.67%,011070,192400,-1500,-0.77,41406,4.65,27161,7.08,180261,1.07,4150,2.16
18,40,풍산,5077,101,+2.42%,103140,48050,-250,-0.52,6395,7.51,6550,7.34,67365,0.71,1000,2.08
19,42,삼성전자우,4858,73,+0.30%,005935,66700,900,1.37,-,-,-,-,-,-,1445,2.17
20,44,포스코퓨처엠,4509,14,-0.79%,003670,318500,0,0.00,1527,208.58,2970,107.25,31922,9.98,300,0.09
21,46,KCC,4451,16,-1.64%,002380,286000,-3000,-1.04,4564,62.66,16813,17.01,695902,0.41,8000,2.80
22,48,기업은행,4076,274,-2.70%,024110,15280,120,0.79,3320,4.6,3602,4.24,36302,0.42,960,6.28
23,52,현대글로비스,3533,19,+1.20%,086280,187400,700,0.37,31729,5.91,32054,5.85,183094,1.02,5700,3.04
24,54,솔루스첨단소재,3372,201,+29.94%,336370,13620,330,2.48,-,-,-,-,7768,1.75,100,0.73
25,56,롯데관광개발,3213,324,+5.71%,032350,9190,170,1.88,-,-,-,-,3223,2.85,0,0.00
26,58,삼성바이오로직스,3106,4,+0.97%,207940,840000,-17000,-1.98,11442,73.41,14281,58.82,126233,6.65,0,0.00

In [24]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   27 non-null     int64
 1   종목명     27 non-null     object
 2   금액      27 non-null     int32
 3   수량      27 non-null     int32
 4   등락      27 non-null     object
 5   종목코드    27 non-null     object
 6   종가      27 non-null     int64
 7   대비      27 non-null     int64
 8   등락률     27 non-null     float64
 9   EPS     27 non-null     object
 10  PER     27 non-null     object
 11  선행 EPS  27 non-null     object
 12  선행 PER  27 non-null     object
 13  BPS     27 non-null     object
 14  PBR     27 non-null     object
 15  주당배당금   27 non-null     int64
 16  배당수익률   27 non-null     float64
dtypes: float64(2), int32(2), int64(4), object(9)
memory usage: 3.5+ KB

### 판다스 특정 조건의 행을 삭제하기

In [25]:
del_index = df_1[ df_1['PBR'] == '-'].index
df_1.drop( del_index, inplace = True )

# df_1 = df_1[ df_1['PBR'] != '-']

In [26]:
df_1 =df_1.dropna()
df_1['PBR'] = df_1['PBR'].astype('float')
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 0 to 26
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   25 non-null     int64
 1   종목명     25 non-null     object
 2   금액      25 non-null     int32
 3   수량      25 non-null     int32
 4   등락      25 non-null     object
 5   종목코드    25 non-null     object
 6   종가      25 non-null     int64
 7   대비      25 non-null     int64
 8   등락률     25 non-null     float64
 9   EPS     25 non-null     object
 10  PER     25 non-null     object
 11  선행 EPS  25 non-null     object
 12  선행 PER  25 non-null     object
 13  BPS     25 non-null     object
 14  PBR     25 non-null     float64
 15  주당배당금   25 non-null     int64
 16  배당수익률   25 non-null     float64
dtypes: float64(3), int32(2), int64(4), object(8)
memory usage: 3.3+ KB

In [ ]:
df_1

In [27]:
df_1 = df_1[df_1['PBR'] < 1 ]
df_1

,index,종목명,금액,수량,등락,종목코드,종가,대비,등락률,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
1,2,현대차,40189,164,+1.46%,005380,243500,-8500,-3.37,28521,8.54,43093,5.65,407147,0.60,7000,2.87
4,8,삼성물산,22161,140,-1.50%,028260,160000,-5000,-3.03,12460,12.84,12830,12.47,164524,0.97,2300,1.44
8,16,하나금융지주,13167,220,-4.07%,086790,64000,100,0.16,11803,5.42,12727,5.03,124935,0.51,3350,5.23
9,18,삼성생명,12426,131,-3.78%,032830,97900,500,0.51,8817,11.1,10071,9.72,124081,0.79,3000,3.06
18,40,풍산,5077,101,+2.42%,103140,48050,-250,-0.52,6395,7.51,6550,7.34,67365,0.71,1000,2.08
21,46,KCC,4451,16,-1.64%,002380,286000,-3000,-1.04,4564,62.66,16813,17.01,695902,0.41,8000,2.80
22,48,기업은행,4076,274,-2.70%,024110,15280,120,0.79,3320,4.6,3602,4.24,36302,0.42,960,6.28

### 날짜 Format strftime 함수

In [28]:
from datetime import date , datetime 
this_year = date.today().year 
this_month = date.today().month
this_day = date.today().day
this_date_2 = str(this_year)+"-"+str(this_month).zfill(2)+"-"+str(this_day).zfill(2)
print( this_date_2 )

today = datetime.now()
today = today.strftime('%Y%m%d')
print( today )

2024-03-28
20240328

### 엑셀 파일에 날짜 Sheet에  업데이트한다.

In [32]:
import pandas as pd 
import numpy as np 
import os 

dir_path = os.path.normpath( os.path.join( os.path.abspath('') , '../resource/forEn_pbr_data' ,'forEn_pbr_daily.xlsx') )
dir_path

writer = pd.ExcelWriter( dir_path , engine = 'openpyxl', mode='a' )
#today = '20240327'
df_1.to_excel( writer, sheet_name = today )

writer.close()

In [41]:
cwd = os.getcwd()
cwd
dir_path_1 = os.path.normpath( os.path.join( cwd, '../resource/forEn_pbr_data' , this_date_2 + '.xlsx'))
df_1.to_excel( dir_path_1, sheet_name = this_date_2  )

In [ ]:
this_date = driver.find_element('xpath', '//*[@id="labDescription"]/em' )
print( this_date.text )