# 1. Selenium  WEB Crawing

### selenuim 과 bs4 로 대체 가능

In [1]:
def add( x, y):
    result = x+y
    return(result)

In [8]:
from selenium import webdriver
from selenium.webdriver.common.by import By
#driver = webdriver.Chrome('./chromedriver')
driver = webdriver.Chrome()
daum_investors  =  'https://finance.daum.net/domestic/influential_investors'

In [9]:
driver.get( daum_investors)

In [10]:
#items = driver.find_element('class name','box_contents')
items = driver.find_element(By.CLASS_NAME,'box_contents')
print( items.text )

순매수 종목 순매도 종목
종목명 금액 - 수량 - 등락률 - 종목명 금액 - 수량 - 등락률 -
SK하이닉스
211,587
1,166
+2.60%
신한지주
52,911
1,108
-5.53%
현대차
40,189
164
+1.46%
LG화학
31,625
71
-1.11%
에이피알
33,931
131
+5.29%
POSCO홀딩스
22,845
53
-0.23%
크래프톤
22,492
87
+4.26%
NAVER
19,759
104
+0.21%
삼성물산
22,161
140
-1.50%
하나투어
14,345
225
-10.26%
이수페타시스
21,423
471
+11.75%
메리츠금융지주
14,196
174
-5.54%
한화에어로스페이스
20,912
95
+3.24%
LG에너지솔루션
13,381
33
+0.74%
현대로템
20,121
596
+3.31%
LG디스플레이
11,517
1,089
-1.94%
하나금융지주
13,167
220
-4.07%
HMM
8,213
526
+0.52%
삼성생명
12,426
131
-3.78%
기아
4,957
43
-0.70%
에코프로머티
11,894
86
-1.42%
LG전자
4,826
50
+0.21%
하이브
10,843
49
+6.92%
LG생활건강
4,803
12
+3.16%
두산밥캣
10,302
192
+11.09%
엔씨소프트
4,594
22
-0.24%
삼성SDI
9,969
20
+1.59%
한올바이오파마
4,546
116
-4.09%
삼성전자
9,696
121
-0.13%
TIGER 미국필라델피아반도체나스닥
4,378
251
+0.14%
현대차우
9,025
56
+2.36%
셀트리온
4,253
24
-1.18%
TIGER 미국필라델피아반도체레버리지(합성)
8,110
351
+0.30%
HD현대일렉트릭
3,813
21
-0.49%
엘앤에프
6,587
35
-1.20%
SK이노베이션
3,707
31
+0.08%
KODEX 200선물인버스2X
6,462
3,172
-0.05%
카카오뱅크
3,662
130
-2.25%
LG이노텍
5,305
27
+1.67%
우리금융지주
3,631
243
-3.37%
풍산
5,077
101
+2.42%
현대제철
3,594
110
+0.15%
삼성전자우
4,858
73
+0.30%
TIGER 미국테크TOP10 INDXX
3,568
200
-0.06%
포스코퓨처엠
4,509
14
-0.79%
KB금융
3,534
50
-3.90%
KCC
4,451
16
-1.64%
한국항공우주
3,395
67
+0.20%
기업은행
4,076
274
-2.70%
S-Oil
3,165
40
-1.64%
TIGER 미국S&P500
3,851
220
+0.57%
부광약품
3,121
392
+2.10%
현대글로비스
3,533
19
+1.20%
KODEX 인버스
3,113
755
-0.12%
솔루스첨단소재
3,372
201
+29.94%
KODEX 코스닥150
3,036
195
-0.81%
롯데관광개발
3,213
324
+5.71%
한화솔루션
2,903
107
-0.37%
삼성바이오로직스
3,106
4
+0.97%
삼성화재
2,847
9
-2.54%

In [11]:
items_ = driver.find_element(By.TAG_NAME, 'table')
items_.text

'코스피\n코스닥\n-\n차트슬라이드'

### List 요소를 4개로 나누어 다시 배열로 만든다.

In [12]:
# List 요소를 4개로 나누어 다시 배열로 만든다.
def list_chuck(arr, n):
    return [arr[i: i + n] for i in range(0, len(arr), n)]

items = driver.find_element('xpath','//*[@id="boxInfluentialInvestors"]/div[2]/div[1]/table')
#print( items.text )
list_items_info = items.text.splitlines() # 텍스트를 라인별로 잘라서 Array 로 만들어 준다.
#print( list_items_info )

del list_items_info[:2]    # 앞에 필요업는 2개 배열요서 제거 
#print( list_items_info )

forEn = list_chuck( list_items_info, 4 )
print( forEn )

[['SK하이닉스', '211,587', '1,166', '+2.60%'], ['신한지주', '52,911', '1,108', '-5.53%'], ['현대차', '40,189', '164', '+1.46%'], ['LG화학', '31,625', '71', '-1.11%'], ['에이피알', '33,931', '131', '+5.29%'], ['POSCO홀딩스', '22,845', '53', '-0.23%'], ['크래프톤', '22,492', '87', '+4.26%'], ['NAVER', '19,759', '104', '+0.21%'], ['삼성물산', '22,161', '140', '-1.50%'], ['하나투어', '14,345', '225', '-10.26%'], ['이수페타시스', '21,423', '471', '+11.75%'], ['메리츠금융지주', '14,196', '174', '-5.54%'], ['한화에어로스페이스', '20,912', '95', '+3.24%'], ['LG에너지솔루션', '13,381', '33', '+0.74%'], ['현대로템', '20,121', '596', '+3.31%'], ['LG디스플레이', '11,517', '1,089', '-1.94%'], ['하나금융지주', '13,167', '220', '-4.07%'], ['HMM', '8,213', '526', '+0.52%'], ['삼성생명', '12,426', '131', '-3.78%'], ['기아', '4,957', '43', '-0.70%'], ['에코프로머티', '11,894', '86', '-1.42%'], ['LG전자', '4,826', '50', '+0.21%'], ['하이브', '10,843', '49', '+6.92%'], ['LG생활건강', '4,803', '12', '+3.16%'], ['두산밥캣', '10,302', '192', '+11.09%'], ['엔씨소프트', '4,594', '22', '-0.24%'], ['삼성SDI', '9,969', '20', '+1.59%'], ['한올바이오파마', '4,546', '116', '-4.09%'], ['삼성전자', '9,696', '121', '-0.13%'], ['TIGER 미국필라델피아반도체나스닥', '4,378', '251', '+0.14%'], ['현대차우', '9,025', '56', '+2.36%'], ['셀트리온', '4,253', '24', '-1.18%'], ['TIGER 미국필라델피아반도체레버리지(합성)', '8,110', '351', '+0.30%'], ['HD현대일렉트릭', '3,813', '21', '-0.49%'], ['엘앤에프', '6,587', '35', '-1.20%'], ['SK이노베이션', '3,707', '31', '+0.08%'], ['KODEX 200선물인버스2X', '6,462', '3,172', '-0.05%'], ['카카오뱅크', '3,662', '130', '-2.25%'], ['LG이노텍', '5,305', '27', '+1.67%'], ['우리금융지주', '3,631', '243', '-3.37%'], ['풍산', '5,077', '101', '+2.42%'], ['현대제철', '3,594', '110', '+0.15%'], ['삼성전자우', '4,858', '73', '+0.30%'], ['TIGER 미국테크TOP10 INDXX', '3,568', '200', '-0.06%'], ['포스코퓨처엠', '4,509', '14', '-0.79%'], ['KB금융', '3,534', '50', '-3.90%'], ['KCC', '4,451', '16', '-1.64%'], ['한국항공우주', '3,395', '67', '+0.20%'], ['기업은행', '4,076', '274', '-2.70%'], ['S-Oil', '3,165', '40', '-1.64%'], ['TIGER 미국S&P500', '3,851', '220', '+0.57%'], ['부광약품', '3,121', '392', '+2.10%'], ['현대글로비스', '3,533', '19', '+1.20%'], ['KODEX 인버스', '3,113', '755', '-0.12%'], ['솔루스첨단소재', '3,372', '201', '+29.94%'], ['KODEX 코스닥150', '3,036', '195', '-0.81%'], ['롯데관광개발', '3,213', '324', '+5.71%'], ['한화솔루션', '2,903', '107', '-0.37%'], ['삼성바이오로직스', '3,106', '4', '+0.97%'], ['삼성화재', '2,847', '9', '-2.54%']]

In [13]:
import pandas as pd

df = pd.DataFrame(forEn)
df

                           0        1      2        3
0                     SK하이닉스  211,587  1,166   +2.60%
1                       신한지주   52,911  1,108   -5.53%
2                        현대차   40,189    164   +1.46%
3                       LG화학   31,625     71   -1.11%
4                       에이피알   33,931    131   +5.29%
5                   POSCO홀딩스   22,845     53   -0.23%
6                       크래프톤   22,492     87   +4.26%
7                      NAVER   19,759    104   +0.21%
8                       삼성물산   22,161    140   -1.50%
9                       하나투어   14,345    225  -10.26%
10                    이수페타시스   21,423    471  +11.75%
11                   메리츠금융지주   14,196    174   -5.54%
12                 한화에어로스페이스   20,912     95   +3.24%
13                  LG에너지솔루션   13,381     33   +0.74%
14                      현대로템   20,121    596   +3.31%
15                   LG디스플레이   11,517  1,089   -1.94%
16                    하나금융지주   13,167    220   -4.07%
17                       HMM    8,213    526   +0.52%
18                      삼성생명   12,426    131   -3.78%
19                        기아    4,957     43   -0.70%
20                    에코프로머티   11,894     86   -1.42%
21                      LG전자    4,826     50   +0.21%
22                       하이브   10,843     49   +6.92%
23                    LG생활건강    4,803     12   +3.16%
24                      두산밥캣   10,302    192  +11.09%
25                     엔씨소프트    4,594     22   -0.24%
26                     삼성SDI    9,969     20   +1.59%
27                   한올바이오파마    4,546    116   -4.09%
28                      삼성전자    9,696    121   -0.13%
29       TIGER 미국필라델피아반도체나스닥    4,378    251   +0.14%
30                      현대차우    9,025     56   +2.36%
31                      셀트리온    4,253     24   -1.18%
32  TIGER 미국필라델피아반도체레버리지(합성)    8,110    351   +0.30%
33                  HD현대일렉트릭    3,813     21   -0.49%
34                      엘앤에프    6,587     35   -1.20%
35                   SK이노베이션    3,707     31   +0.08%
36          KODEX 200선물인버스2X    6,462  3,172   -0.05%
37                     카카오뱅크    3,662    130   -2.25%
38                     LG이노텍    5,305     27   +1.67%
39                    우리금융지주    3,631    243   -3.37%
40                        풍산    5,077    101   +2.42%
41                      현대제철    3,594    110   +0.15%
42                     삼성전자우    4,858     73   +0.30%
43     TIGER 미국테크TOP10 INDXX    3,568    200   -0.06%
44                    포스코퓨처엠    4,509     14   -0.79%
45                      KB금융    3,534     50   -3.90%
46                       KCC    4,451     16   -1.64%
47                    한국항공우주    3,395     67   +0.20%
48                      기업은행    4,076    274   -2.70%
49                     S-Oil    3,165     40   -1.64%
50            TIGER 미국S&P500    3,851    220   +0.57%
51                      부광약품    3,121    392   +2.10%
52                    현대글로비스    3,533     19   +1.20%
53                 KODEX 인버스    3,113    755   -0.12%
54                   솔루스첨단소재    3,372    201  +29.94%
55              KODEX 코스닥150    3,036    195   -0.81%
56                    롯데관광개발    3,213    324   +5.71%
57                     한화솔루션    2,903    107   -0.37%
58                  삼성바이오로직스    3,106      4   +0.97%
59                      삼성화재    2,847      9   -2.54%

In [14]:
df.columns =['종목명','금액','수량','등락']
df.info()
df_1 = df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     60 non-null     object
 1   금액      60 non-null     object
 2   수량      60 non-null     object
 3   등락      60 non-null     object
dtypes: object(4)
memory usage: 2.0+ KB

### List 에서 홀수째 열만 뽑아 낸다.

In [18]:
mList = [ x for x in range(1, df_1['종목명'].count(), 2 )]
mList

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [19]:
df['금액'] = df['금액'].str.replace(',','')
df['수량'] = df['수량'].str.replace(',','')
# df.drop( index..)
df = df.drop(mList)
df

AttributeError: Can only use .str accessor with string values!

In [17]:
df['금액'] = df['금액'].astype('int')
df['수량'] = df['수량'].astype('int')
df.dtypes

종목명    object
금액      int32
수량      int32
등락     object
dtype: object

# 2.Selenium + BeautifulSoup으로 Crawling

In [10]:
from bs4 import BeautifulSoup
from selenium import webdriver
import urllib 
import pandas as pd
daum_investors  =  'https://finance.daum.net/domestic/influential_investors?market=KOSPI'
"""
html_table = urllib.request.urlopen( daum_investors ).read() 
"""

driver = webdriver.Chrome()
driver.get(daum_investors)
html_table = driver.page_source

soup = BeautifulSoup( html_table, "html.parser")

for table in soup.find_all('table'):
    print( table )

table = pd.read_html( str( soup), flavor="bs4")
print( table[1] )

<table class="tab">
<colgroup>
<col width="100"/>
<col width="100"/>
<col width="*"/>
</colgroup>
<tbody>
<tr>
<td class="on"><a href="?market=KOSPI" title="코스피">코스피</a></td>
<td class=""><a href="?market=KOSDAQ" title="코스닥">코스닥</a></td>
<td class="last">
<a class="btnChart" href="/domestic/chart_slides/influential_investors?market=KOSPI" title="차트슬라이드"><i>-</i>차트슬라이드</a>
</td>
</tr>
</tbody>
</table>
<table>
<colgroup>
<col width="*"/>
<col width="74"/>
<col width="64"/>
<col width="74"/>
<col width="120"/>
<col width="74"/>
<col width="64"/>
<col width="74"/>
</colgroup>
<thead>
<tr>
<th class="red" colspan="4">순매수 종목</th>
<th class="blue" colspan="4">순매도 종목</th>
</tr>
<tr>
<th class="lAlign">종목명</th>
<th class="rAlign">
<a class="" data-field-name="straightPurchasePrice" data-field-type="buy" href="javascript:void(0)">
                금액 <i>-</i>
</a>
</th>
<th class="rAlign">
            &lt;a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="buy"&gt;
                수량 <i>-</i>

</th>
<th class="rAlign last">
            &lt;a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="buy"&gt;
                등락률 <i>-</i>

</th>
<th class="pL lAlign">종목명</th>
<th class="rAlign">
<a class="on" data-field-name="straightPurchasePrice" data-field-type="sell" href="javascript:void(0)">
                금액 <i>-</i>
</a>
</th>
<th class="rAlign">
            &lt;a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="sell"&gt;
                수량 <i>-</i>

</th>
<th class="rAlign last">
            &lt;a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="sell"&gt;
                등락률 <i>-</i>

</th>
</tr>
</thead>
<tbody>
<tr class="first">
<td>
<a class="txt" href="/quotes/A005930">삼성전자</a>
</td>
<td>
<span class="num">641,267</span>
</td>
<td>
<span class="num">7,817</span>
</td>
<td class="pR">
<span class="num up">+1.98%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A007660">이수페타시스</a>
</td>
<td>
<span class="num">22,172</span>
</td>
<td>
<span class="num">512</span>
</td>
<td class="pR">
<span class="num down">-5.79%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A000660">SK하이닉스</a>
</td>
<td>
<span class="num">75,755</span>
</td>
<td>
<span class="num">414</span>
</td>
<td class="pR">
<span class="num up">+2.69%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A066570">LG전자</a>
</td>
<td>
<span class="num">17,103</span>
</td>
<td>
<span class="num">179</span>
</td>
<td class="pR">
<span class="num down">-1.76%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A068270">셀트리온</a>
</td>
<td>
<span class="num">67,487</span>
</td>
<td>
<span class="num">354</span>
</td>
<td class="pR">
<span class="num up">+4.03%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A252670">KODEX 200선물인버스2X</a>
</td>
<td>
<span class="num">16,280</span>
</td>
<td>
<span class="num">8,225</span>
</td>
<td class="pR">
<span class="num down">-0.60%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A064350">현대로템</a>
</td>
<td>
<span class="num">54,538</span>
</td>
<td>
<span class="num">1,479</span>
</td>
<td class="pR">
<span class="num up">+6.98%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A278470">에이피알</a>
</td>
<td>
<span class="num">15,461</span>
</td>
<td>
<span class="num">61</span>
</td>
<td class="pR">
<span class="num down">-4.58%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A005935">삼성전자우</a>
</td>
<td>
<span class="num">37,412</span>
</td>
<td>
<span class="num">550</span>
</td>
<td class="pR">
<span class="num up">+1.19%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A035420">NAVER</a>
</td>
<td>
<span class="num">14,569</span>
</td>
<td>
<span class="num">78</span>
</td>
<td class="pR">
<span class="num up">+0.16%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A028260">삼성물산</a>
</td>
<td>
<span class="num">20,255</span>
</td>
<td>
<span class="num">127</span>
</td>
<td class="pR">
<span class="num down">-1.00%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A373220">LG에너지솔루션</a>
</td>
<td>
<span class="num">12,323</span>
</td>
<td>
<span class="num">31</span>
</td>
<td class="pR">
<span class="num down">-1.62%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A006400">삼성SDI</a>
</td>
<td>
<span class="num">17,895</span>
</td>
<td>
<span class="num">38</span>
</td>
<td class="pR">
<span class="num down">-1.36%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A001040">CJ</a>
</td>
<td>
<span class="num">11,510</span>
</td>
<td>
<span class="num">90</span>
</td>
<td class="pR">
<span class="num up">+6.22%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A105560">KB금융</a>
</td>
<td>
<span class="num">16,050</span>
</td>
<td>
<span class="num">228</span>
</td>
<td class="pR">
<span class="num down">-1.14%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A051910">LG화학</a>
</td>
<td>
<span class="num">8,526</span>
</td>
<td>
<span class="num">19</span>
</td>
<td class="pR">
<span class="num down">-0.23%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A079550">LIG넥스원</a>
</td>
<td>
<span class="num">12,647</span>
</td>
<td>
<span class="num">70</span>
</td>
<td class="pR">
<span class="num up">+0.85%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A086280">현대글로비스</a>
</td>
<td>
<span class="num">8,283</span>
</td>
<td>
<span class="num">47</span>
</td>
<td class="pR">
<span class="num down">-3.60%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A000150">두산</a>
</td>
<td>
<span class="num">10,772</span>
</td>
<td>
<span class="num">66</span>
</td>
<td class="pR">
<span class="num up">+2.98%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A001440">대한전선</a>
</td>
<td>
<span class="num">8,108</span>
</td>
<td>
<span class="num">758</span>
</td>
<td class="pR">
<span class="num up">+1.56%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A000270">기아</a>
</td>
<td>
<span class="num">10,352</span>
</td>
<td>
<span class="num">94</span>
</td>
<td class="pR">
<span class="num down">-1.61%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A096770">SK이노베이션</a>
</td>
<td>
<span class="num">7,341</span>
</td>
<td>
<span class="num">63</span>
</td>
<td class="pR">
<span class="num down">-2.03%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A267250">HD현대</a>
</td>
<td>
<span class="num">9,627</span>
</td>
<td>
<span class="num">135</span>
</td>
<td class="pR">
<span class="num up">+4.35%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A128940">한미약품</a>
</td>
<td>
<span class="num">6,610</span>
</td>
<td>
<span class="num">20</span>
</td>
<td class="pR">
<span class="num down">-2.63%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A042700">한미반도체</a>
</td>
<td>
<span class="num">9,337</span>
</td>
<td>
<span class="num">70</span>
</td>
<td class="pR">
<span class="num down">-0.22%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A103590">일진전기</a>
</td>
<td>
<span class="num">6,593</span>
</td>
<td>
<span class="num">299</span>
</td>
<td class="pR">
<span class="num down">-1.47%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A086790">하나금융지주</a>
</td>
<td>
<span class="num">8,434</span>
</td>
<td>
<span class="num">145</span>
</td>
<td class="pR">
<span class="num down">-2.04%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A454910">두산로보틱스</a>
</td>
<td>
<span class="num">6,562</span>
</td>
<td>
<span class="num">73</span>
</td>
<td class="pR">
<span class="num down">-0.11%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A000810">삼성화재</a>
</td>
<td>
<span class="num">8,189</span>
</td>
<td>
<span class="num">27</span>
</td>
<td class="pR">
<span class="num down">-0.97%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A036570">엔씨소프트</a>
</td>
<td>
<span class="num">6,409</span>
</td>
<td>
<span class="num">32</span>
</td>
<td class="pR">
<span class="num down">-3.50%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A032830">삼성생명</a>
</td>
<td>
<span class="num">7,692</span>
</td>
<td>
<span class="num">83</span>
</td>
<td class="pR">
<span class="num down">-3.35%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A001570">금양</a>
</td>
<td>
<span class="num">5,280</span>
</td>
<td>
<span class="num">40</span>
</td>
<td class="pR">
<span class="num up">+2.21%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A005380">현대차</a>
</td>
<td>
<span class="num">7,555</span>
</td>
<td>
<span class="num">32</span>
</td>
<td class="pR">
<span class="num down">-1.69%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A011200">HMM</a>
</td>
<td>
<span class="num">5,263</span>
</td>
<td>
<span class="num">334</span>
</td>
<td class="pR">
<span class="num down">-0.19%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A024110">기업은행</a>
</td>
<td>
<span class="num">7,020</span>
</td>
<td>
<span class="num">521</span>
</td>
<td class="pR">
<span class="num down">-3.23%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A003160">디아이</a>
</td>
<td>
<span class="num">5,051</span>
</td>
<td>
<span class="num">367</span>
</td>
<td class="pR">
<span class="num up">+12.63%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A005490">POSCO홀딩스</a>
</td>
<td>
<span class="num">6,740</span>
</td>
<td>
<span class="num">16</span>
</td>
<td class="pR">
<span class="num up">+0.24%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A139480">이마트</a>
</td>
<td>
<span class="num">5,032</span>
</td>
<td>
<span class="num">74</span>
</td>
<td class="pR">
<span class="num down">-0.88%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A011930">신성이엔지</a>
</td>
<td>
<span class="num">5,355</span>
</td>
<td>
<span class="num">2,244</span>
</td>
<td class="pR">
<span class="num up">+11.51%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A042660">한화오션</a>
</td>
<td>
<span class="num">4,951</span>
</td>
<td>
<span class="num">179</span>
</td>
<td class="pR">
<span class="num up">+0.73%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A005070">코스모신소재</a>
</td>
<td>
<span class="num">5,332</span>
</td>
<td>
<span class="num">33</span>
</td>
<td class="pR">
<span class="num down">-1.42%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A017670">SK텔레콤</a>
</td>
<td>
<span class="num">4,925</span>
</td>
<td>
<span class="num">93</span>
</td>
<td class="pR">
<span class="num down">-1.50%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A034220">LG디스플레이</a>
</td>
<td>
<span class="num">5,193</span>
</td>
<td>
<span class="num">483</span>
</td>
<td class="pR">
<span class="num up">+1.61%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A032640">LG유플러스</a>
</td>
<td>
<span class="num">4,919</span>
</td>
<td>
<span class="num">492</span>
</td>
<td class="pR">
<span class="num down">-0.80%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A450080">에코프로머티</a>
</td>
<td>
<span class="num">4,655</span>
</td>
<td>
<span class="num">36</span>
</td>
<td class="pR">
<span class="num down">-2.10%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A307950">현대오토에버</a>
</td>
<td>
<span class="num">4,850</span>
</td>
<td>
<span class="num">34</span>
</td>
<td class="pR">
<span class="num down">-2.31%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A012330">현대모비스</a>
</td>
<td>
<span class="num">4,611</span>
</td>
<td>
<span class="num">18</span>
</td>
<td class="pR">
<span class="num down">-2.49%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A329180">HD현대중공업</a>
</td>
<td>
<span class="num">4,541</span>
</td>
<td>
<span class="num">38</span>
</td>
<td class="pR">
<span class="num down">-0.59%</span>
</td>
</tr>
<tr class="last">
<td>
<a class="txt" href="/quotes/A035720">카카오</a>
</td>
<td>
<span class="num">3,987</span>
</td>
<td>
<span class="num">74</span>
</td>
<td class="pR">
<span class="num down">-1.29%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A323410">카카오뱅크</a>
</td>
<td>
<span class="num">4,516</span>
</td>
<td>
<span class="num">163</span>
</td>
<td class="pR">
<span class="num down">-1.96%</span>
</td>
</tr>
<tr class="line">
<td>
<a class="txt" href="/quotes/A207940">삼성바이오로직스</a>
</td>
<td>
<span class="num">3,885</span>
</td>
<td>
<span class="num">5</span>
</td>
<td class="pR">
<span class="num down">-0.24%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A011790">SKC</a>
</td>
<td>
<span class="num">4,437</span>
</td>
<td>
<span class="num">38</span>
</td>
<td class="pR">
<span class="num down">-7.02%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A066970">엘앤에프</a>
</td>
<td>
<span class="num">3,762</span>
</td>
<td>
<span class="num">22</span>
</td>
<td class="pR">
<span class="num down">-1.19%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A051900">LG생활건강</a>
</td>
<td>
<span class="num">4,395</span>
</td>
<td>
<span class="num">11</span>
</td>
<td class="pR">
<span class="num down">-1.68%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A402340">SK스퀘어</a>
</td>
<td>
<span class="num">3,762</span>
</td>
<td>
<span class="num">48</span>
</td>
<td class="pR">
<span class="num up">+0.51%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A006260">LS</a>
</td>
<td>
<span class="num">3,816</span>
</td>
<td>
<span class="num">33</span>
</td>
<td class="pR">
<span class="num down">-0.70%</span>
</td>
</tr>
<tr class="">
<td>
<a class="txt" href="/quotes/A316140">우리금융지주</a>
</td>
<td>
<span class="num">3,651</span>
</td>
<td>
<span class="num">257</span>
</td>
<td class="pR">
<span class="num down">-1.85%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A011780">금호석유</a>
</td>
<td>
<span class="num">3,699</span>
</td>
<td>
<span class="num">27</span>
</td>
<td class="pR">
<span class="num down">-3.35%</span>
</td>
</tr>
<tr class="last last">
<td>
<a class="txt" href="/quotes/A030200">KT</a>
</td>
<td>
<span class="num">3,443</span>
</td>
<td>
<span class="num">90</span>
</td>
<td class="pR">
<span class="num down">-0.66%</span>
</td>
<td class="pL">
<a class="txt" href="/quotes/A008930">한미사이언스</a>
</td>
<td>
<span class="num">3,677</span>
</td>
<td>
<span class="num">92</span>
</td>
<td class="pR">
<span class="num down">-13.64%</span>
</td>
</tr>
</tbody>
</table>

      순매수 종목
         종목명    금액 -
0       삼성전자  641267  \
1     SK하이닉스   75755
2       셀트리온   67487
3       현대로템   54538
4      삼성전자우   37412
5       삼성물산   20255
6      삼성SDI   17895
7       KB금융   16050
8     LIG넥스원   12647
9         두산   10772
10        기아   10352
11      HD현대    9627
12     한미반도체    9337
13    하나금융지주    8434
14      삼성화재    8189
15      삼성생명    7692
16       현대차    7555
17      기업은행    7020
18  POSCO홀딩스    6740
19     신성이엔지    5355
20    코스모신소재    5332
21   LG디스플레이    5193
22    에코프로머티    4655
23     현대모비스    4611
24       카카오    3987
25  삼성바이오로직스    3885
26      엘앤에프    3762
27     SK스퀘어    3762
28    우리금융지주    3651
29        KT    3443


   <a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="buy">  수량 -
0                                                7817                                                                \
1                                                 414
2                                                 354
3                                                1479
4                                                 550
5                                                 127
6                                                  38
7                                                 228
8                                                  70
9                                                  66
10                                                 94
11                                                135
12                                                 70
13                                                145
14                                                 27
15                                                 83
16                                                 32
17                                                521
18                                                 16
19                                               2244
20                                                 33
21                                                483
22                                                 36
23                                                 18
24                                                 74
25                                                  5
26                                                 22
27                                                 48
28                                                257
29                                                 90


   <a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="buy">  등락률 -
0                                              +1.98%                                                     \
1                                              +2.69%
2                                              +4.03%
3                                              +6.98%
4                                              +1.19%
5                                              -1.00%
6                                              -1.36%
7                                              -1.14%
8                                              +0.85%
9                                              +2.98%
10                                             -1.61%
11                                             +4.35%
12                                             -0.22%
13                                             -2.04%
14                                             -0.97%
15                                             -3.35%
16                                             -1.69%
17                                             -3.23%
18                                             +0.24%
19                                            +11.51%
20                                             -1.42%
21                                             +1.61%
22                                             -2.10%
23                                             -2.49%
24                                             -1.29%
25                                             -0.24%
26                                             -1.19%
27                                             +0.51%
28                                             -1.85%
29                                             -0.66%

              순매도 종목
                 종목명   금액 -
0             이수페타시스  22172  \
1               LG전자  17103
2   KODEX 200선물인버스2X  16280
3               에이피알  15461
4              NAVER  14569
5           LG에너지솔루션  12323
6                 CJ  11510
7               LG화학   8526
8             현대글로비스   8283
9               대한전선   8108
10           SK이노베이션   7341
11              한미약품   6610
12              일진전기   6593
13            두산로보틱스   6562
14             엔씨소프트   6409
15                금양   5280
16               HMM   5263
17               디아이   5051
18               이마트   5032
19              한화오션   4951
20             SK텔레콤   4925
21            LG유플러스   4919
22            현대오토에버   4850
23           HD현대중공업   4541
24             카카오뱅크   4516
25               SKC   4437
26            LG생활건강   4395
27                LS   3816
28              금호석유   3699
29            한미사이언스   3677


   <a href="javascript:void(0)" class="" data-field-name="straightPurchaseVolume" ,="" data-field-type="sell">  수량 -
0                                                 512                                                                 \
1                                                 179
2                                                8225
3                                                  61
4                                                  78
5                                                  31
6                                                  90
7                                                  19
8                                                  47
9                                                 758
10                                                 63
11                                                 20
12                                                299
13                                                 73
14                                                 32
15                                                 40
16                                                334
17                                                367
18                                                 74
19                                                179
20                                                 93
21                                                492
22                                                 34
23                                                 38
24                                                163
25                                                 38
26                                                 11
27                                                 33
28                                                 27
29                                                 92


   <a href="javascript:void(0)" class="" data-field-name="changeRate" ,="" data-field-type="sell">  등락률 -
0                                              -5.79%
1                                              -1.76%
2                                              -0.60%
3                                              -4.58%
4                                              +0.16%
5                                              -1.62%
6                                              +6.22%
7                                              -0.23%
8                                              -3.60%
9                                              +1.56%
10                                             -2.03%
11                                             -2.63%
12                                             -1.47%
13                                             -0.11%
14                                             -3.50%
15                                             +2.21%
16                                             -0.19%
17                                            +12.63%
18                                             -0.88%
19                                             +0.73%
20                                             -1.50%
21                                             -0.80%
22                                             -2.31%
23                                             -0.59%
24                                             -1.96%
25                                             -7.02%
26                                             -1.68%
27                                             -0.70%
28                                             -3.35%
29                                            -13.64%

###  Pandas: drop a level from a multi-level column index?

cols = pd.MultiIndex.from_tuples([("a", "b"), ("a", "c")])

In [12]:
df_1 = table[1]
df_1.columns

df_1 = df_1.drop( columns = [('순매도 종목')] )

C:\Users\star_\AppData\Local\Temp\ipykernel_10808\2694043953.py:4: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df_1 = df_1.drop( columns = [('순매도 종목')] )

### Pandas: drop a level from a multi-level column index  only?

In [14]:
df_1.columns = df_1.columns.droplevel(0)
df_1
#df_1.columns = ['종목명','금액','수량','등락률']

,종목명,금액 -,"<a href=""javascript:void(0)"" class="""" data-field-name=""straightPurchaseVolume"" ,="""" data-field-type=""buy""> 수량 -","<a href=""javascript:void(0)"" class="""" data-field-name=""changeRate"" ,="""" data-field-type=""buy""> 등락률 -"
0,삼성전자,641267,7817,+1.98%
1,SK하이닉스,75755,414,+2.69%
2,셀트리온,67487,354,+4.03%
3,현대로템,54538,1479,+6.98%
4,삼성전자우,37412,550,+1.19%
5,삼성물산,20255,127,-1.00%
6,삼성SDI,17895,38,-1.36%
7,KB금융,16050,228,-1.14%
8,LIG넥스원,12647,70,+0.85%
9,두산,10772,66,+2.98%
10,기아,10352,94,-1.61%
11,HD현대,9627,135,+4.35%
12,한미반도체,9337,70,-0.22%
13,하나금융지주,8434,145,-2.04%
14,삼성화재,8189,27,-0.97%
15,삼성생명,7692,83,-3.35%
16,현대차,7555,32,-1.69%
17,기업은행,7020,521,-3.23%
18,POSCO홀딩스,6740,16,+0.24%
19,신성이엔지,5355,2244,+11.51%
20,코스모신소재,5332,33,-1.42%
21,LG디스플레이,5193,483,+1.61%
22,에코프로머티,4655,36,-2.10%
23,현대모비스,4611,18,-2.49%
24,카카오,3987,74,-1.29%
25,삼성바이오로직스,3885,5,-0.24%
26,엘앤에프,3762,22,-1.19%
27,SK스퀘어,3762,48,+0.51%
28,우리금융지주,3651,257,-1.85%
29,KT,3443,90,-0.66%

In [16]:
df_1.columns = ['종목명','금액','수량','등락률']
df_1

         종목명      금액    수량      등락률
0       삼성전자  641267  7817   +1.98%
1     SK하이닉스   75755   414   +2.69%
2       셀트리온   67487   354   +4.03%
3       현대로템   54538  1479   +6.98%
4      삼성전자우   37412   550   +1.19%
5       삼성물산   20255   127   -1.00%
6      삼성SDI   17895    38   -1.36%
7       KB금융   16050   228   -1.14%
8     LIG넥스원   12647    70   +0.85%
9         두산   10772    66   +2.98%
10        기아   10352    94   -1.61%
11      HD현대    9627   135   +4.35%
12     한미반도체    9337    70   -0.22%
13    하나금융지주    8434   145   -2.04%
14      삼성화재    8189    27   -0.97%
15      삼성생명    7692    83   -3.35%
16       현대차    7555    32   -1.69%
17      기업은행    7020   521   -3.23%
18  POSCO홀딩스    6740    16   +0.24%
19     신성이엔지    5355  2244  +11.51%
20    코스모신소재    5332    33   -1.42%
21   LG디스플레이    5193   483   +1.61%
22    에코프로머티    4655    36   -2.10%
23     현대모비스    4611    18   -2.49%
24       카카오    3987    74   -1.29%
25  삼성바이오로직스    3885     5   -0.24%
26      엘앤에프    3762    22   -1.19%
27     SK스퀘어    3762    48   +0.51%
28    우리금융지주    3651   257   -1.85%
29        KT    3443    90   -0.66%

### 필요업는 항목의 제목으로 제거하기

In [20]:
df = df_1
df = df[~df['종목명'].str.contains('TIGER')]
df = df[~df['종목명'].str.contains('KODEX')]
df.sort_values( by ='금액', ascending = False )

         종목명      금액    수량      등락률
0       삼성전자  641267  7817   +1.98%
1     SK하이닉스   75755   414   +2.69%
2       셀트리온   67487   354   +4.03%
3       현대로템   54538  1479   +6.98%
4      삼성전자우   37412   550   +1.19%
5       삼성물산   20255   127   -1.00%
6      삼성SDI   17895    38   -1.36%
7       KB금융   16050   228   -1.14%
8     LIG넥스원   12647    70   +0.85%
9         두산   10772    66   +2.98%
10        기아   10352    94   -1.61%
11      HD현대    9627   135   +4.35%
12     한미반도체    9337    70   -0.22%
13    하나금융지주    8434   145   -2.04%
14      삼성화재    8189    27   -0.97%
15      삼성생명    7692    83   -3.35%
16       현대차    7555    32   -1.69%
17      기업은행    7020   521   -3.23%
18  POSCO홀딩스    6740    16   +0.24%
19     신성이엔지    5355  2244  +11.51%
20    코스모신소재    5332    33   -1.42%
21   LG디스플레이    5193   483   +1.61%
22    에코프로머티    4655    36   -2.10%
23     현대모비스    4611    18   -2.49%
24       카카오    3987    74   -1.29%
25  삼성바이오로직스    3885     5   -0.24%
26      엘앤에프    3762    22   -1.19%
27     SK스퀘어    3762    48   +0.51%
28    우리금융지주    3651   257   -1.85%
29        KT    3443    90   -0.66%

## Pandas: getting rid of the multiindex

In [19]:
#df.columns = df.columns.map(lambda x: x[1])
df = df.reset_index()

"""
df.columns = df.columns.map(''.join)
#Or if need remove level use droplevel:

df.columns = df.columns.droplevel(0)
#If need access to values is possible use xs:

df = df.xs('CID', axis=1, level=1)
#You can also check:
#What is the difference between size and count in pandas?


EDIT:
For remove MultiIndex is another solution select by ['FID'].


df = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()
Samples (also added rename_axis for nicer output):

df = pd.DataFrame({'CID':[2,2,3],
                   'FE':[5,5,6],
                   'FID':[1,7,9]})

print (df)
   CID  FE  FID
0    2   5    1
1    2   5    7
2    3   6    9

df = df.groupby(by=['CID','FE'])['FID']
       .count()
       .unstack()
       .reset_index()
       .rename_axis(None, axis=1)

print (df)    
   CID    5    6
0    2  2.0  NaN
1    3  NaN  1.0
"""

"\ndf.columns = df.columns.map(''.join)\n#Or if need remove level use droplevel:\n\ndf.columns = df.columns.droplevel(0)\n#If need access to values is possible use xs:\n\ndf = df.xs('CID', axis=1, level=1)\n#You can also check:\n#What is the difference between size and count in pandas?\n\n\nEDIT:\nFor remove MultiIndex is another solution select by ['FID'].\n\n\ndf = df.groupby(by=['CID','FE'])['FID'].count().unstack().reset_index()\nSamples (also added rename_axis for nicer output):\n\ndf = pd.DataFrame({'CID':[2,2,3],\n                   'FE':[5,5,6],\n                   'FID':[1,7,9]})\n\nprint (df)\n   CID  FE  FID\n0    2   5    1\n1    2   5    7\n2    3   6    9\n\ndf = df.groupby(by=['CID','FE'])['FID']\n       .count()\n       .unstack()\n       .reset_index()\n       .rename_axis(None, axis=1)\n\nprint (df)    \n   CID    5    6\n0    2  2.0  NaN\n1    3  NaN  1.0\n"

In [ ]:
df

In [20]:
df.index = list( range(0, df['종목명'].count())) 
df

    index        종목명      금액    수량       등락
0       0     SK하이닉스  211587  1166   +2.60%
1       2        현대차   40189   164   +1.46%
2       4       에이피알   33931   131   +5.29%
3       6       크래프톤   22492    87   +4.26%
4       8       삼성물산   22161   140   -1.50%
5      10     이수페타시스   21423   471  +11.75%
6      12  한화에어로스페이스   20912    95   +3.24%
7      14       현대로템   20121   596   +3.31%
8      16     하나금융지주   13167   220   -4.07%
9      18       삼성생명   12426   131   -3.78%
10     20     에코프로머티   11894    86   -1.42%
11     22        하이브   10843    49   +6.92%
12     24       두산밥캣   10302   192  +11.09%
13     26      삼성SDI    9969    20   +1.59%
14     28       삼성전자    9696   121   -0.13%
15     30       현대차우    9025    56   +2.36%
16     34       엘앤에프    6587    35   -1.20%
17     38      LG이노텍    5305    27   +1.67%
18     40         풍산    5077   101   +2.42%
19     42      삼성전자우    4858    73   +0.30%
20     44     포스코퓨처엠    4509    14   -0.79%
21     46        KCC    4451    16   -1.64%
22     48       기업은행    4076   274   -2.70%
23     52     현대글로비스    3533    19   +1.20%
24     54    솔루스첨단소재    3372   201  +29.94%
25     56     롯데관광개발    3213   324   +5.71%
26     58   삼성바이오로직스    3106     4   +0.97%

### KRX 에서 받은 현재 전종목 PBR PER DIV 엑셀과 Join

In [21]:
import os , sys 
from os import listdir
dirname = os.path.abspath('')
dirname = os.path.normpath( os.path.join( dirname , '../examples[data-source]/f_xls/data_krx' ) )
last_file = listdir( dirname  )[-1]
last_file 
file_path = os.path.join( dirname ,  last_file )
#df_fn = pd.read_excel('data_3608_20220912.xlsx')
df_fn = pd.read_excel(file_path)

c:\python38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [26]:
df_fn['종목명'] = df_fn['종목명'].str.strip()
df_fn = df_fn.drop( columns =['등락률'])

In [27]:
df_fn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2623 entries, 0 to 2622
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    2623 non-null   object
 1   종목명     2623 non-null   object
 2   종가      2623 non-null   int64
 3   대비      2623 non-null   int64
 4   EPS     2623 non-null   object
 5   PER     2623 non-null   object
 6   선행 EPS  2623 non-null   object
 7   선행 PER  2623 non-null   object
 8   BPS     2623 non-null   object
 9   PBR     2623 non-null   object
 10  주당배당금   2623 non-null   int64
 11  배당수익률   2623 non-null   float64
dtypes: float64(1), int64(3), object(8)
memory usage: 246.0+ KB

In [28]:
df_2 = df.merge(df_fn, how='left')
df_2

,종목명,금액,수량,등락률,종목코드,종가,대비,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,삼성전자,641267,7817,+1.98%,005930,78900.0,-400.0,8057,9.79,4709,16.76,57822,1.36,1444.0,1.83
1,SK하이닉스,75755,414,+2.69%,000660,169800.0,-200.0,3242,52.38,12187,13.93,92004,1.85,1200.0,0.71
2,셀트리온,67487,354,+4.03%,068270,188200.0,2400.0,3751,50.17,3406,55.25,28937,6.5,375.0,0.20
3,현대로템,54538,1479,+6.98%,064350,32400.0,1100.0,1812,17.88,2216,14.62,13930,2.33,0.0,0.00
4,삼성전자우,37412,550,+1.19%,005935,66700.0,900.0,-,-,-,-,-,-,1445.0,2.17
5,삼성물산,20255,127,-1.00%,028260,160000.0,-5000.0,12460,12.84,12830,12.47,164524,0.97,2300.0,1.44
6,삼성SDI,17895,38,-1.36%,006400,472500.0,17000.0,29191,16.19,29027,16.28,251948,1.88,1030.0,0.22
7,KB금융,16050,228,-1.14%,105560,74900.0,-1200.0,10955,6.84,12563,5.96,124124,0.6,2950.0,3.94
8,LIG넥스원,12647,70,+0.85%,079550,167300.0,2600.0,5641,29.66,9595,17.44,42909,3.9,1500.0,0.90
9,두산,10772,66,+2.98%,000150,147000.0,-3600.0,-,-,9498,15.48,132422,1.11,2000.0,1.36
10,기아,10352,94,-1.61%,000270,112900.0,-2800.0,13495,8.37,22218,5.08,98117,1.15,3500.0,3.10
11,HD현대,9627,135,+4.35%,267250,68900.0,-1200.0,19933,3.46,9811,7.02,105921,0.65,4600.0,6.68
12,한미반도체,9337,70,-0.22%,042700,93800.0,0.0,939,99.89,1515,61.93,4008,23.4,200.0,0.21
13,하나금융지주,8434,145,-2.04%,086790,64000.0,100.0,11803,5.42,12727,5.03,124935,0.51,3350.0,5.23
14,삼성화재,8189,27,-0.97%,000810,335000.0,-8000.0,30113,11.12,39032,8.58,276525,1.21,13800.0,4.12
15,삼성생명,7692,83,-3.35%,032830,97900.0,500.0,8817,11.1,10071,9.72,124081,0.79,3000.0,3.06
16,현대차,7555,32,-1.69%,005380,243500.0,-8500.0,28521,8.54,43093,5.65,407147,0.6,7000.0,2.87
17,기업은행,7020,521,-3.23%,024110,15280.0,120.0,3320,4.6,3602,4.24,36302,0.42,960.0,6.28
18,POSCO홀딩스,6740,16,+0.24%,005490,428500.0,500.0,41456,10.34,29060,14.75,692323,0.62,12000.0,2.80
19,신성이엔지,5355,2244,+11.51%,011930,2370.0,20.0,168,14.11,200,11.86,1036,2.29,0.0,0.00
20,코스모신소재,5332,33,-1.42%,005070,169200.0,-300.0,901,187.79,2230,75.87,8099,20.89,0.0,0.00
21,LG디스플레이,5193,483,+1.61%,034220,10750.0,-460.0,-,-,-,-,25521,0.42,0.0,0.00
22,에코프로머티,4655,36,-2.10%,450080,149800.0,-900.0,294,509.52,-,-,5428,27.6,0.0,0.00
23,현대모비스,4611,18,-2.49%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,카카오,3987,74,-1.29%,035720,53600.0,0.0,3106,17.26,1116,48.03,22893,2.34,60.0,0.11
25,삼성바이오로직스,3885,5,-0.24%,207940,840000.0,-17000.0,11442,73.41,14281,58.82,126233,6.65,0.0,0.00
26,엘앤에프,3762,22,-1.19%,066970,186100.0,9600.0,8269,22.51,620,299.99,38454,4.84,500.0,0.27
27,SK스퀘어,3762,48,+0.51%,402340,80000.0,3000.0,1837,43.55,7439,10.75,118972,0.67,0.0,0.00
28,우리금융지주,3651,257,-1.85%,316140,15200.0,-90.0,4191,3.63,4049,3.75,39505,0.38,1130.0,7.43
29,KT,3443,90,-0.66%,030200,38750.0,400.0,5209,7.44,4851,7.99,64880,0.6,1960.0,5.06

In [29]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     30 non-null     object
 1   금액      30 non-null     int64
 2   수량      30 non-null     int64
 3   등락률     30 non-null     object
 4   종목코드    29 non-null     object
 5   종가      29 non-null     float64
 6   대비      29 non-null     float64
 7   EPS     29 non-null     object
 8   PER     29 non-null     object
 9   선행 EPS  29 non-null     object
 10  선행 PER  29 non-null     object
 11  BPS     29 non-null     object
 12  PBR     29 non-null     object
 13  주당배당금   29 non-null     float64
 14  배당수익률   29 non-null     float64
dtypes: float64(4), int64(2), object(9)
memory usage: 3.6+ KB

### 판다스 특정 조건의 행을 삭제하기

In [31]:
del_index = df_2[ df_2['PBR'] == '-'].index
df_2.drop( del_index, inplace = True )

# df_1 = df_1[ df_1['PBR'] != '-']

In [32]:
df_2 =df_2.dropna()
df_2['PBR'] = df_2['PBR'].astype('float')
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 29
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목명     28 non-null     object
 1   금액      28 non-null     int64
 2   수량      28 non-null     int64
 3   등락률     28 non-null     object
 4   종목코드    28 non-null     object
 5   종가      28 non-null     float64
 6   대비      28 non-null     float64
 7   EPS     28 non-null     object
 8   PER     28 non-null     object
 9   선행 EPS  28 non-null     object
 10  선행 PER  28 non-null     object
 11  BPS     28 non-null     object
 12  PBR     28 non-null     float64
 13  주당배당금   28 non-null     float64
 14  배당수익률   28 non-null     float64
dtypes: float64(5), int64(2), object(8)
memory usage: 3.5+ KB

C:\Users\star_\AppData\Local\Temp\ipykernel_10808\795994724.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['PBR'] = df_2['PBR'].astype('float')

In [33]:
df_2

,종목명,금액,수량,등락률,종목코드,종가,대비,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
0,삼성전자,641267,7817,+1.98%,005930,78900.0,-400.0,8057,9.79,4709,16.76,57822,1.36,1444.0,1.83
1,SK하이닉스,75755,414,+2.69%,000660,169800.0,-200.0,3242,52.38,12187,13.93,92004,1.85,1200.0,0.71
2,셀트리온,67487,354,+4.03%,068270,188200.0,2400.0,3751,50.17,3406,55.25,28937,6.50,375.0,0.20
3,현대로템,54538,1479,+6.98%,064350,32400.0,1100.0,1812,17.88,2216,14.62,13930,2.33,0.0,0.00
5,삼성물산,20255,127,-1.00%,028260,160000.0,-5000.0,12460,12.84,12830,12.47,164524,0.97,2300.0,1.44
6,삼성SDI,17895,38,-1.36%,006400,472500.0,17000.0,29191,16.19,29027,16.28,251948,1.88,1030.0,0.22
7,KB금융,16050,228,-1.14%,105560,74900.0,-1200.0,10955,6.84,12563,5.96,124124,0.60,2950.0,3.94
8,LIG넥스원,12647,70,+0.85%,079550,167300.0,2600.0,5641,29.66,9595,17.44,42909,3.90,1500.0,0.90
9,두산,10772,66,+2.98%,000150,147000.0,-3600.0,-,-,9498,15.48,132422,1.11,2000.0,1.36
10,기아,10352,94,-1.61%,000270,112900.0,-2800.0,13495,8.37,22218,5.08,98117,1.15,3500.0,3.10
11,HD현대,9627,135,+4.35%,267250,68900.0,-1200.0,19933,3.46,9811,7.02,105921,0.65,4600.0,6.68
12,한미반도체,9337,70,-0.22%,042700,93800.0,0.0,939,99.89,1515,61.93,4008,23.40,200.0,0.21
13,하나금융지주,8434,145,-2.04%,086790,64000.0,100.0,11803,5.42,12727,5.03,124935,0.51,3350.0,5.23
14,삼성화재,8189,27,-0.97%,000810,335000.0,-8000.0,30113,11.12,39032,8.58,276525,1.21,13800.0,4.12
15,삼성생명,7692,83,-3.35%,032830,97900.0,500.0,8817,11.1,10071,9.72,124081,0.79,3000.0,3.06
16,현대차,7555,32,-1.69%,005380,243500.0,-8500.0,28521,8.54,43093,5.65,407147,0.60,7000.0,2.87
17,기업은행,7020,521,-3.23%,024110,15280.0,120.0,3320,4.6,3602,4.24,36302,0.42,960.0,6.28
18,POSCO홀딩스,6740,16,+0.24%,005490,428500.0,500.0,41456,10.34,29060,14.75,692323,0.62,12000.0,2.80
19,신성이엔지,5355,2244,+11.51%,011930,2370.0,20.0,168,14.11,200,11.86,1036,2.29,0.0,0.00
20,코스모신소재,5332,33,-1.42%,005070,169200.0,-300.0,901,187.79,2230,75.87,8099,20.89,0.0,0.00
21,LG디스플레이,5193,483,+1.61%,034220,10750.0,-460.0,-,-,-,-,25521,0.42,0.0,0.00
22,에코프로머티,4655,36,-2.10%,450080,149800.0,-900.0,294,509.52,-,-,5428,27.60,0.0,0.00
24,카카오,3987,74,-1.29%,035720,53600.0,0.0,3106,17.26,1116,48.03,22893,2.34,60.0,0.11
25,삼성바이오로직스,3885,5,-0.24%,207940,840000.0,-17000.0,11442,73.41,14281,58.82,126233,6.65,0.0,0.00
26,엘앤에프,3762,22,-1.19%,066970,186100.0,9600.0,8269,22.51,620,299.99,38454,4.84,500.0,0.27
27,SK스퀘어,3762,48,+0.51%,402340,80000.0,3000.0,1837,43.55,7439,10.75,118972,0.67,0.0,0.00
28,우리금융지주,3651,257,-1.85%,316140,15200.0,-90.0,4191,3.63,4049,3.75,39505,0.38,1130.0,7.43
29,KT,3443,90,-0.66%,030200,38750.0,400.0,5209,7.44,4851,7.99,64880,0.60,1960.0,5.06

In [34]:
df_2 = df_2[df_2['PBR'] < 1 ]
df_2

,종목명,금액,수량,등락률,종목코드,종가,대비,EPS,PER,선행 EPS,선행 PER,BPS,PBR,주당배당금,배당수익률
5,삼성물산,20255,127,-1.00%,028260,160000.0,-5000.0,12460,12.84,12830,12.47,164524,0.97,2300.0,1.44
7,KB금융,16050,228,-1.14%,105560,74900.0,-1200.0,10955,6.84,12563,5.96,124124,0.60,2950.0,3.94
11,HD현대,9627,135,+4.35%,267250,68900.0,-1200.0,19933,3.46,9811,7.02,105921,0.65,4600.0,6.68
13,하나금융지주,8434,145,-2.04%,086790,64000.0,100.0,11803,5.42,12727,5.03,124935,0.51,3350.0,5.23
15,삼성생명,7692,83,-3.35%,032830,97900.0,500.0,8817,11.1,10071,9.72,124081,0.79,3000.0,3.06
16,현대차,7555,32,-1.69%,005380,243500.0,-8500.0,28521,8.54,43093,5.65,407147,0.60,7000.0,2.87
17,기업은행,7020,521,-3.23%,024110,15280.0,120.0,3320,4.6,3602,4.24,36302,0.42,960.0,6.28
18,POSCO홀딩스,6740,16,+0.24%,005490,428500.0,500.0,41456,10.34,29060,14.75,692323,0.62,12000.0,2.80
21,LG디스플레이,5193,483,+1.61%,034220,10750.0,-460.0,-,-,-,-,25521,0.42,0.0,0.00
27,SK스퀘어,3762,48,+0.51%,402340,80000.0,3000.0,1837,43.55,7439,10.75,118972,0.67,0.0,0.00
28,우리금융지주,3651,257,-1.85%,316140,15200.0,-90.0,4191,3.63,4049,3.75,39505,0.38,1130.0,7.43
29,KT,3443,90,-0.66%,030200,38750.0,400.0,5209,7.44,4851,7.99,64880,0.60,1960.0,5.06

### 날짜 Format strftime 함수

In [35]:
from datetime import date , datetime 
this_year = date.today().year 
this_month = date.today().month
this_day = date.today().day
this_date_2 = str(this_year)+"-"+str(this_month).zfill(2)+"-"+str(this_day).zfill(2)
print( this_date_2 )

today = datetime.now()
today = today.strftime('%Y%m%d')
print( today )

2024-03-30
20240330

### 엑셀 파일에 날짜 Sheet에  업데이트한다.

In [38]:
import pandas as pd 
import numpy as np 
import os 

dir_path = os.path.normpath( os.path.join( os.path.abspath('') , '../resource/forEn_pbr_data' ,'forEn_pbr_daily.xlsx') )
dir_path

writer = pd.ExcelWriter( dir_path , engine = 'openpyxl', mode='a' )
#today = '20240327'
df_2.to_excel( writer, sheet_name = today )

writer.close()

In [39]:
cwd = os.getcwd()
cwd
dir_path_1 = os.path.normpath( os.path.join( cwd, '../resource/forEn_pbr_data' , this_date_2 + '.xlsx'))
df_2.to_excel( dir_path_1, sheet_name = this_date_2  )

In [ ]:
this_date = driver.find_element('xpath', '//*[@id="labDescription"]/em' )
print( this_date.text )